import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  de: {
    // Header
    search: 'Nach Events suchen...',
    allDays: 'Alle Tage',
    friday: 'Freitag',
    saturday: 'Samstag',
    sunday: 'Sonntag',
    
    // Days (for translation)
    freitag: 'Freitag',
    samstag: 'Samstag',
    sonntag: 'Sonntag',
    filterVenues: 'Venues filtern',
    filterEventTypes: 'Event-Typen filtern',
    days: 'Tage',
    venues: 'Venues',
    events: 'Events',
    clearFilters: 'Filter zurücksetzen',
    gridView: 'Raster',
    listView: 'Liste',
    
    // Venues
    draussen: 'Neue Ufer',
    oben: 'Salon',
    unten: '2000er',
    
    // Event Types
    performance: 'Performance',
    dj: 'DJ',
    workshop: 'Workshop',
    live: 'Live-Konzert',
    interaktiv: 'Interaktiv',
    
    // Grid
    venue: 'VENUE',
    time: 'ZEIT',
    
    // Event Details
    eventDetails: 'Event-Details',
    day: 'Tag',
    venue_label: 'Veranstaltungsort',
    description: 'Beschreibung',
    links: 'Links',
    
    // Empty States
    noEvents: 'Keine Events gefunden',
    noEventsDesc: 'Versuche deine Filter oder Suchbegriffe anzupassen',
    
    // Common
    close: 'Schließen',
    
    // Event descriptions (translatable)
    welcomeDinnerDesc: 'Beginne dein Festival-Erlebnis mit köstlichem Streetfood und Community-Vibes',
    fireshowDesc: 'Spektakuläre Feuershow, die die Nacht erleuchtet',
    soundJourneyDesc: 'Immersive Klanglandschaft und Gespräch ab 23:00',
    karaokeDesc: 'Sing dich aus voller Kehle mit Freunden in unserer gemütlichen Karaoke-Lounge',
    docuMachlandDesc: 'Dokumentarfilm-Screening und Diskussion über die vier Dimensionen der Nachhaltigkeit',
    yogaFlowDesc: 'Körper-Geist-Verbindung durch fließende Yoga-Bewegungen',
    aerobicTherapyDesc: 'Bewegungstherapie, die Tanz und Wellness kombiniert',
    letterOpeningDesc: 'Interaktive Brieföffnungs-Performance-Kunst',
    soundJourneyLiveDesc: 'Live-Looping Klanglandschaft',
    bowling: 'Interaktives Bowling mit Sekt - Spaß und Spiele für alle',
    
    // FAQ
    faq: 'FAQ',
    faqs: 'FAQs',
    frequentlyAskedQuestions: 'Häufig gestellte Fragen',
    back: 'Zurück',
    
    // Navigation
    timetable: 'Timetable',
    tickets: 'Soli-Beiträge',
    
    // Tickets / Soli-Beiträge
    standardTickets: 'Standard Soli-Beiträge',
    standardTicketsDesc: 'Standard Soli-Beiträge beinhalten eine generell sehr entspannte 2-Stunden-Schicht in den unten aufgeführten Rollen. Du kannst deine bevorzugte Option im nächsten Schritt auswählen.',
    earlyBird: 'Early Bird',
    normal: 'Normal Bird',
    reducedTickets: 'Reduzierte Soli-Beiträge',
    reducedTicketsDesc: 'Diese Soli-Beiträge erhalten einen Preisnachlass aufgrund der Intensität / zusätzlichen Verantwortung der zugehörigen Positionen im Vergleich zu Standard Soli-Beiträgen. Bitte beachte: Einige dieser Positionen sind ausschließlich für Personen mit vorheriger Erfahrung / Expertise verfügbar.',
    chooseThisTicket: 'Diesen Soli-Beitrag wählen',
    roleDescriptions: 'Rollenbeschreibungen',
    bar: 'Bar',
    kuechenhilfe: 'Küchenhilfe',
    springerRunner: 'Springer-Runner',
    springerToilet: 'Springer-Toilet',
    abbau: 'Festival-Abbau',
    aufbau: 'Festival-Aufbau',
    awareness: 'Awareness',
    schichtleitung: 'Schichtleitung',
    selectRole: 'Rolle auswählen...',
    roleDescriptionsDesc: 'Detaillierte Rollenbeschreibungen werden hier verfügbar sein.',
    onlyWithExperience: 'Nur mit Erfahrung / Organisatoren-Zustimmung',
    clearSelection: 'Auswahl entfernen',
    ticketTypesExplanation: 'Soli-Beitrags-System Übersicht',
    ticketTypesExplanationDesc: 'Hier findest du eine Übersicht über die verschiedenen Soli-Beitrags-Typen, die für das Kollektiv Spinnen Festival verfügbar sind.',
    ticketTypesNote: 'Aufgrund der inhärenten Non-Profit / Community-basierten Natur von Kollektiv Spinnen beinhalten alle Soli-Beiträge für unser Festival die Übernahme einer Schicht in einer der verschiedenen Rollen, die benötigt werden, um all dies möglich zu machen. Die Länge der Schichten variiert zwischen Standard Soli-Beiträgen & Reduzierten Soli-Beiträgen.',
    ticketTypesNoteAdditional: 'Du wirst deine Festival-Rolle im folgenden Prozess auswählen und wirst später per E-Mail kontaktiert, um deine spezifische Schichtzeit festzulegen.',
    earlyBirdNormalTitle: 'Early Bird / Normal Bird',
    earlyBirdNormalDesc: 'Beide Soli-Beitrags-Typen sind als Early Bird oder Normal Bird erhältlich, abhängig davon, wann du deinen Soli-Beitrag leistest / Verfügbarkeit (Es wird eine begrenzte Anzahl von Early-Bird-Soli-Beiträgen geben).',
    whatIsIncludedTitle: 'Was ist in meinem Soli-Beitrag enthalten?',
    whatIsIncludedDesc: 'Alle Soli-Beiträge beinhalten:',
    ticketIncludesAccess: 'Zugang zum Festival',
    ticketIncludesSleeping: 'Zugang zu Indoor-Schlafmöglichkeiten (abhängig von Ankunftszeit / Tag)',
    ticketIncludesDrinks: 'Alkoholfreie & alkoholische Getränke an der Bar',
    ticketIncludesMeals: '2 Mahlzeiten pro Tag in der Kantine',
    standardTicketType: 'Standard Soli-Beiträge',
    standardTicketTypeDesc: 'Standard Soli-Beiträge beinhalten die Übernahme einer 2-Stunden-Schicht während des Festivals. Du kannst zwischen Early Bird und Normal Bird Soli-Beitrags-Optionen wählen, abhängig von der Verfügbarkeit.',
    reducedTicketType: 'Reduzierte Soli-Beiträge',
    reducedTicketTypeDesc: 'Reduzierte Soli-Beiträge bieten einen Preisnachlass aufgrund der Intensität oder zusätzlichen Verantwortung der zugehörigen Positionen. Diese Soli-Beiträge sind für spezielle Rollen wie Aufbau, Abbau, Awareness oder Schichtleitung verfügbar.',
    reducedTicketTypeReductions: 'Die Preisnachlässe im Detail:\n• Festival-Aufbau (20% Nachlass)\n• Festival-Abbau (40% Nachlass - in Form einer Rückerstattung nach dem Festival)\n• Awareness (20% Nachlass)\n• Schichtleitung (50% Nachlass)\n\nDiese Nachlässe gelten für sowohl Early Bird als auch Normal Bird Varianten.',
    
    // FAQ Page
    searchFAQs: 'FAQs durchsuchen...',
    noFAQsAvailable: 'Keine FAQs verfügbar',
    checkBackLater: 'Schau später nochmal vorbei für häufig gestellte Fragen.',
    found: 'gefunden',
    result: 'Ergebnis',
    results: 'Ergebnisse',
    noResultsFound: 'Keine Ergebnisse gefunden',
    noFAQsMatchSearch: 'Keine FAQs entsprechen der Suche',
    clearSearch: 'Suche zurücksetzen',
    allgemein: 'Allgemein',
    
    // Ticket / Soli-Beitrag Checkout
    checkout: 'Checkout',
    paymentProcess: 'Bestätigungsprozess',
    ticketType: 'Soli-Beitrags-Typ',
    selectedRole: 'Ausgewählte Rolle',
    nA: 'N/A',
    checkoutPlaceholder: 'Dies ist eine Platzhalter-Checkout-Seite. Die vollständige Checkout-Funktionalität wird hier implementiert.',
    ticketSummary: 'Soli-Beitrags-Zusammenfassung',
    price: 'Beitrag',
    purchaserInformation: 'Persönliche Daten',
    fullName: 'Vollständiger Name',
    firstName: 'Vorname',
    lastName: 'Nachname',
    enterFullName: 'Gib deinen vollständigen Namen ein',
    enterEmail: 'Gib deine E-Mail-Adresse ein',
    notes: 'Zusätzliche Notizen',
    optional: 'Optional',
    anyAdditionalInformation: 'Weitere Informationen...',
    paymentNote: 'Hinweis: Die Zahlungsabwicklung erfolgt separat. Du erhältst Zahlungsanweisungen per E-Mail nach dem Absenden dieses Formulars.',
    confirmPurchase: 'Kauf bestätigen',
    paymentConfirmed: 'Überweisung bestätigt',
    processing: 'Wird verarbeitet...',
    ticketPurchaseCreated: 'Soli-Beitrags-Kauf erstellt',
    ticketPurchaseCreatedDesc: 'Dein Soli-Beitrags-Kauf wurde registriert. Du erhältst in Kürze eine Bestätigungs-E-Mail.',
    missingTicketInformation: 'Fehlende Soli-Beitrags-Informationen',
    soldOut: 'Ausverkauft',
    soldOutDesc: 'Dieser Soli-Beitrags-Typ ist nicht mehr verfügbar',
    validationError: 'Validierungsfehler',
    failedToProcessPurchase: 'Soli-Beitrags-Kauf konnte nicht verarbeitet werden',
    remainingTickets: 'Verbleibende Soli-Beiträge',
    unlimited: 'Unbegrenzt',
    pleaseCheckFormErrors: 'Bitte überprüfe das Formular auf Fehler',
    payWithPayPal: 'Überweise deinen Soli-Beitrag über PayPal Money-Pool',
    checklistItem1: 'Gib deine Daten in das Formular ein',
    checklistItem2: 'Generiere deinen persönlichen Referenzcode (Drücke den Generieren-Button)',
    checklistItem3: 'Überweise deinen Soli-Beitrag über den/die PayPal-Link(s) zu unserem Money Pool mit deinem Referenzcode (sehr wichtig!)',
    checklistItem4: 'Klicke auf den Button "Überweisung bestätigt"',
    generateReference: 'Referenzcode generieren',
    referenceCodeGenerated: 'Ihr Referenzcode',
    copyReferenceCode: 'Referenzcode kopieren',
    referenceCodeCopied: 'Referenzcode kopiert!',
    allChecklistItemsRequired: 'Bitte alle Checklistenpunkte abschließen',
    paypalQRCode: 'PayPal QR-Code',
    paypalLink: 'PayPal Link',
    scanQRCode: 'Scanne den QR-Code mit deinem Handy, um zu bezahlen',
    orClickLink: 'oder klicke auf den Link',
    paypalPaymentInstructions: 'Bitte überweise den Betrag von {amount}€ über PayPal, bevor du das Formular absendest.',
    pleaseFillNameBeforeGenerating: 'Bitte fülle Vorname und Nachname aus, bevor du den Referenzcode generierst',
    referenceCodeGeneratedSuccessfully: 'Referenzcode erfolgreich generiert',
    pleaseGenerateReferenceBeforeConfirming: 'Bitte generiere einen Referenzcode, bevor du die Zahlung bestätigst',
    checklist: 'Checkliste',
    pleaseFollowChecklist: 'Bitte folge der Checkliste oben, um sicherzustellen, dass der Bestätigungsprozess korrekt abläuft',
    validEmailFormat: '✓ Gültiges E-Mail-Format',
    qrCodeImage: 'QR-Code Bild',
    placeQRCodeInPublicFolder: 'Platziere paypal-qr-code.png im public Ordner',
    onlyClickAfterPayment: 'Klicke nur auf den Button "Überweisung bestätigt", nachdem du deinen Soli-Beitrag über PayPal überwiesen hast und die Checkliste oben auf der Seite abgeschlossen hast',
    dataStorageConsent: 'Ich stimme zu, dass meine Daten gespeichert werden dürfen, um mich bezüglich meiner Schichtbuchung zu kontaktieren.',
    dataStorageConsentRequired: 'Bitte stimme der Datenspeicherung zu, um fortzufahren.',
    
    // Footer
    sitemap: 'Sitemap',
    sitemapShort: 'Map',
    backToTop: 'Nach oben',
    backToTopShort: 'Oben',
    
    // Header
    admin: 'Admin',
    login: 'Anmelden',
    
    // Auth
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    welcomeBack: 'Willkommen zurück bei Kollektiv Spinnen',
    createAccount: 'Erstelle dein Konto',
    email: 'E-Mail',
    password: 'Passwort',
    dontHaveAccount: 'Noch kein Konto? Registrieren',
    alreadyHaveAccount: 'Bereits ein Konto? Anmelden',
    backToFestival: 'Zurück zum Festival',
    authenticationError: 'Authentifizierungsfehler',
    welcomeBackToast: 'Willkommen zurück!',
    signedInSuccessfully: 'Du hast dich erfolgreich angemeldet.',
    accountCreated: 'Konto erstellt!',
    checkEmailVerify: 'Bitte überprüfe deine E-Mail, um dein Konto zu verifizieren.',
    error: 'Fehler',
    unexpectedError: 'Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut.',
    accessDenied: 'Zugriff verweigert',
    noAdminPermissions: 'Du hast keine Administratorrechte.',
    
    // Admin Page
    adminDashboard: 'Admin Dashboard',
    aboutUs: 'Über uns',
    signOut: 'Abmelden',
    eventsManagement: 'Event-Verwaltung',
    faqManagement: 'FAQ-Verwaltung',
    ticketSettings: 'Soli-Beitrags-Einstellungen',
    aboutUsManagement: 'Über uns Verwaltung',
    addEvent: 'Event hinzufügen',
    addFAQ: 'FAQ hinzufügen',
    searchEvents: 'Events nach Titel, Venue, Tag, Typ oder Beschreibung suchen...',
    showing: 'Zeige',
    of: 'von',
    noEventsFound: 'Keine Events gefunden',
    event: 'Event',
    events_plural: 'Events',
    editEvent: 'Event bearbeiten',
    editFAQ: 'FAQ bearbeiten',
    createNewEvent: 'Neues Event erstellen',
    createNewFAQ: 'Neue FAQ erstellen',
    hidden: 'Verborgen',
    makeVisible: 'Öffentlich sichtbar machen',
    hideFromPublic: 'Vor der Öffentlichkeit verbergen',
    loadingTicketSettings: 'Soli-Beitrags-Einstellungen werden geladen...',
    loadingAboutPageData: 'Über uns Seiten-Daten werden geladen...',
    earlyBirdTicketSettings: 'Early Bird Soli-Beitrags-Einstellungen',
    enableEarlyBirdTickets: 'Early Bird Soli-Beiträge aktivieren',
    enableEarlyBirdTicketsDesc: 'Wenn aktiviert, stehen Early Bird Soli-Beitrags-Optionen für Gäste zur Verfügung',
    earlyBirdCutoffDate: 'Early Bird Stichtag & Uhrzeit',
    earlyBirdCutoffDesc: 'Early Bird Soli-Beiträge sind nach diesem Datum und dieser Uhrzeit nicht mehr verfügbar',
    ticketAvailabilityLimits: 'Soli-Beitrags-Verfügbarkeits-Limits',
    setMaximumTickets: 'Setze die maximale Anzahl verfügbarer Soli-Beiträge für jede Rolle. Leer lassen für unbegrenzt.',
    standardTickets_plural: 'Standard Soli-Beiträge',
    reducedTickets_plural: 'Reduzierte Soli-Beiträge',
    limit: 'Limit',
    ticketPricing: 'Soli-Beitrags-Preisgestaltung',
    setPricesForRoles: 'Setze Preise für jede Soli-Beitrags-Rolle (in Euro). Leer lassen für Standard-Preise.',
    earlyBirdPrice: 'Early Bird Preis (€)',
    normalPrice: 'Normal Bird Preis (€)',
    saveTicketSettings: 'Soli-Beitrags-Einstellungen speichern',
    pageContent: 'Seiteninhalt',
    title: 'Titel',
    content: 'Inhalt',
    saveContent: 'Inhalt speichern',
    festivalPhotos: 'Festival-Fotos',
    uploadNewPhoto: 'Neues Foto hochladen',
    upload: 'Hochladen',
    noPhotosUploaded: 'Noch keine Fotos hochgeladen',
    alignment: 'Ausrichtung',
    size: 'Größe',
    caption: 'Bildunterschrift',
    optionalCaption: 'Optionale Bildunterschrift',
    save: 'Speichern',
    cancel: 'Abbrechen',
    left: 'Links',
    center: 'Zentriert',
    right: 'Rechts',
    small: 'Klein',
    medium: 'Mittel',
    large: 'Groß',
    fullWidth: 'Volle Breite',
    photoUploadedSuccessfully: 'Foto erfolgreich hochgeladen',
    photoUpdatedSuccessfully: 'Foto erfolgreich aktualisiert',
    photoDeletedSuccessfully: 'Foto erfolgreich gelöscht',
    failedToUploadPhoto: 'Foto konnte nicht hochgeladen werden',
    failedToUpdatePhoto: 'Foto konnte nicht aktualisiert werden',
    failedToDeletePhoto: 'Foto konnte nicht gelöscht werden',
    areYouSureDeletePhoto: 'Bist du sicher, dass du dieses Foto löschen möchtest?',
    areYouSureDeleteEvent: 'Bist du sicher, dass du dieses Event löschen möchtest?',
    areYouSureDeleteFAQ: 'Bist du sicher, dass du diese FAQ löschen möchtest?',
    eventUpdatedSuccessfully: 'Event erfolgreich aktualisiert',
    eventCreatedSuccessfully: 'Event erfolgreich erstellt',
    eventDeletedSuccessfully: 'Event erfolgreich gelöscht',
    eventHiddenFromPublic: 'Event vor der Öffentlichkeit verborgen',
    eventMadeVisibleToPublic: 'Event für die Öffentlichkeit sichtbar gemacht',
    faqUpdatedSuccessfully: 'FAQ erfolgreich aktualisiert',
    faqCreatedSuccessfully: 'FAQ erfolgreich erstellt',
    faqDeletedSuccessfully: 'FAQ erfolgreich gelöscht',
    faqHiddenFromPublic: 'FAQ vor der Öffentlichkeit verborgen',
    faqMadeVisibleToPublic: 'FAQ für die Öffentlichkeit sichtbar gemacht',
    ticketSettingsUpdatedSuccessfully: 'Soli-Beitrags-Einstellungen erfolgreich aktualisiert',
    aboutPageContentUpdatedSuccessfully: 'Über uns Seiteninhalt erfolgreich aktualisiert',
    failedToLoadEvents: 'Events konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToLoadFAQs: 'FAQs konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToLoadTicketSettings: 'Soli-Beitrags-Einstellungen konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToLoadAboutPageData: 'Über uns Seiten-Daten konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToSaveEvent: 'Event konnte nicht gespeichert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToDeleteEvent: 'Event konnte nicht gelöscht werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToUpdateEventVisibility: 'Event-Sichtbarkeit konnte nicht aktualisiert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToSaveFAQ: 'FAQ konnte nicht gespeichert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToDeleteFAQ: 'FAQ konnte nicht gelöscht werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToUpdateFAQVisibility: 'FAQ-Sichtbarkeit konnte nicht aktualisiert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToSaveTicketSettings: 'Ticket-Einstellungen konnten nicht gespeichert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToSaveAboutPageContent: 'Über uns Seiteninhalt konnte nicht gespeichert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    hiddenMode: 'Versteckter Modus',
    showAll: 'Alle anzeigen',
    forTheEarlyBirdVariant: 'für die Early Bird Variante',
    forTheNormalVariant: 'für die Normal Bird Variante',
    remaining: 'verbleibend',
    
    // Confirmed Soli-Contributions
    purchases: 'Bestätigte Soli-Beiträge',
    loadingPurchases: 'Bestätigte Soli-Beiträge werden geladen...',
    noPurchasesYet: 'Noch keine bestätigten Soli-Beiträge',
    ticketPurchases: 'Bestätigte Soli-Beiträge',
    confirm: 'Bestätigen',
    purchaseConfirmedSuccessfully: 'Soli-Beitrag erfolgreich bestätigt',
    failedToLoadTicketPurchases: 'Bestätigte Soli-Beiträge konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToConfirmPurchase: 'Soli-Beitrag konnte nicht bestätigt werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    pending: 'Ausstehend',
    confirmed: 'Bestätigt',
    cancelled: 'Storniert',
    earlyBirdTotalLimit: 'Early Bird Gesamtlimit',
    earlyBirdTotalLimitDesc: 'Setze die Gesamtanzahl verfügbarer Early-Bird-Soli-Beiträge für alle Rollen. Leer lassen für unbegrenzt. Early-Bird-Soli-Beiträge werden automatisch nicht mehr verfügbar, wenn dieses Limit erreicht ist.',
    normalTicketSettings: 'Normal Bird Soli-Beitrags-Einstellungen',
    normalTotalLimit: 'Normal Bird Soli-Beitrags-Gesamtlimit',
    normalTotalLimitDesc: 'Setze die Gesamtanzahl verfügbarer Normal Bird Soli-Beiträge für alle Rollen. Leer lassen für unbegrenzt. Normal Bird Soli-Beiträge werden automatisch nicht mehr verfügbar, wenn dieses Limit erreicht ist.',
    universalTicketLimits: 'Universelle Soli-Beitrags-Limits',
    universalTicketLimitsDesc: 'Setze die maximale Anzahl von Soli-Beiträgen, die für jeden Soli-Beitrags-Typ über alle Rollen hinweg geleistet werden können. Diese Limits gelten universell für sowohl Early-Bird- als auch Normal Bird Soli-Beiträge.',
    
    // Admin - Data Loading
    warning: 'Warnung',
    failedToLoadDataSources: 'Fehler beim Laden von {count} Datenquelle(n). Einige Funktionen sind möglicherweise nicht verfügbar.',
    dataSourceEvents: 'Events',
    dataSourceFAQs: 'FAQs',
    dataSourceTicketSettings: 'Ticket-Einstellungen',
    dataSourceAboutPage: 'Über uns Seite',
    dataSourceTicketPurchases: 'Bestätigte Soli-Beiträge',
    dataSourceUnknown: 'Datenquelle {index}',
    
    // Admin - URL Validation
    invalidURL: 'Ungültige URL',
    urlMustStartWithHttp: 'URL muss mit http:// oder https:// beginnen',
    pleaseEnterValidURL: 'Bitte gib eine gültige URL ein',
    lowerNumbersAppearFirst: 'Niedrigere Zahlen erscheinen zuerst. Verwende dies, um die Reihenfolge der FAQs zu steuern.',
    
    // Admin - Ticket Purchases
    pendingSoliContributions: 'Ausstehende Soli-Beiträge',
    checkedSoliContributions: 'Geprüfte Soli-Beiträge',
    loadingCheckedPurchases: 'Geprüfte Soli-Beiträge werden geladen...',
    noCheckedPurchasesYet: 'Noch keine geprüften Soli-Beiträge',
    checked: 'Geprüft',
    payment: 'Zahlung',
    notes: 'Notizen',
    failedToUpdateCheckedState: 'Geprüft-Status konnte nicht aktualisiert werden',
    
    // Admin - Event Form
    eventTitle: 'Titel',
    eventTime: 'Zeit',
    startTime: 'Startzeit',
    endTime: 'Endzeit',
    eventDay: 'Tag',
    eventVenue: 'Veranstaltungsort',
    eventType: 'Typ',
    descriptionGerman: 'Beschreibung (Deutsch)',
    descriptionEnglish: 'Beschreibung (Englisch)',
    germanDescriptionPlaceholder: 'Deutsche Beschreibung...',
    englishDescriptionPlaceholder: 'Englische Beschreibung...',
    selectDay: 'Tag auswählen',
    selectVenue: 'Veranstaltungsort auswählen',
    selectType: 'Typ auswählen',
    links: 'Links',
    platformPlaceholder: 'Plattform (z.B. Instagram, Spotify)',
    urlPlaceholder: 'URL',
    addLink: 'Link hinzufügen',
    updateEvent: 'Event aktualisieren',
    createEvent: 'Event erstellen',
    
    // Admin - FAQ Form
    question: 'Frage',
    answer: 'Antwort',
    enterQuestionPlaceholder: 'Gib die häufig gestellte Frage ein...',
    enterAnswerPlaceholder: 'Gib die Antwort auf die Frage ein...',
    displayOrder: 'Anzeigereihenfolge',
    visibleToPublic: 'Öffentlich sichtbar',
    updateFAQ: 'FAQ aktualisieren',
    createFAQ: 'FAQ erstellen',
    
    // Admin - Ticket Settings Form
    standardTickets: 'Standard Soli-Beiträge',
    reducedTickets: 'Reduzierte Soli-Beiträge',
    unlimited: 'Unbegrenzt',
    limit: 'Limit',
    
    // Admin - About Page Form
    editFAQ: 'FAQ bearbeiten'
  },
  en: {
    // Header
    search: 'Search events...',
    allDays: 'All Days',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    
    // Days (for translation)
    freitag: 'Friday',
    samstag: 'Saturday',
    sonntag: 'Sunday',
    filterVenues: 'Filter venues',
    filterEventTypes: 'Filter event types',
    days: 'Days',
    venues: 'Venues',
    events: 'Events',
    clearFilters: 'Clear Filters',
    gridView: 'Grid',
    listView: 'List',
    
    // Venues
    draussen: 'Neue Ufer',
    oben: 'Salon',
    unten: '2000er',
    
    // Event Types
    performance: 'Performance',
    dj: 'DJ',
    workshop: 'Workshop',
    live: 'Live Concert',
    interaktiv: 'Interactive',
    
    // Grid
    venue: 'VENUE',
    time: 'TIME',
    
    // Event Details
    eventDetails: 'Event Details',
    day: 'Day',
    venue_label: 'Venue',
    description: 'Description',
    links: 'Links',
    
    // Empty States
    noEvents: 'No events found',
    noEventsDesc: 'Try adjusting your filters or search query',
    
    // Common
    close: 'Close',
    
    // Event descriptions (translatable)
    welcomeDinnerDesc: 'Start your festival experience with delicious street food and community vibes',
    fireshowDesc: 'Spectacular fire performance lighting up the night',
    soundJourneyDesc: 'Immersive sound journey and conversation starting at 23:00',
    karaokeDesc: 'Sing your heart out with friends in our cozy karaoke lounge',
    docuMachlandDesc: 'Documentary screening and discussion about the four dimensions of sustainability',
    yogaFlowDesc: 'Mind-body connection through flowing yoga movements',
    aerobicTherapyDesc: 'Movement therapy combining dance and wellness',
    letterOpeningDesc: 'Interactive letter-opening performance art',
    soundJourneyLiveDesc: 'Live-Looping Soundjourney',
    bowling: 'Interactive bowling with sparkling wine - fun and games for everyone',
    
    // FAQ
    faq: 'FAQ',
    faqs: 'FAQs',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    back: 'Back',
    
    // Navigation
    timetable: 'Timetable',
    tickets: 'Soli-Contributions',
    
    // Tickets / Soli-Contributions
    standardTickets: 'Standard Soli-Contributions',
    standardTicketsDesc: 'Standard Soli-Contributions include one generally very relaxed 2hr shift in the roles listed below, you can select your preferred option in the next step.',
    earlyBird: 'Early Bird',
    normal: 'Normal Bird',
    reducedTickets: 'Reduced Soli-Contributions',
    reducedTicketsDesc: 'These Soli-Contributions receive a price discount due to the intensity / additional responsibility of the related positions when compared to Standard Soli-Contributions. Please note: Some of these positions are exclusively available to individuals with prior experience / expertise.',
    chooseThisTicket: 'Choose This Soli-Contribution',
    roleDescriptions: 'Role Descriptions',
    bar: 'Bar',
    kuechenhilfe: 'Kitchen Helper',
    springerRunner: 'Springer-Runner',
    springerToilet: 'Springer-Toilet',
    abbau: 'Festival-Breakdown',
    aufbau: 'Festival-Setup',
    awareness: 'Awareness',
    schichtleitung: 'Shift Management',
    selectRole: 'Select a role...',
    roleDescriptionsDesc: 'Detailed role descriptions will be available here.',
    onlyWithExperience: 'Only with experience / organiser consent',
    clearSelection: 'Clear selection',
    ticketTypesExplanation: 'Soli-Contribution System Overview',
    ticketTypesExplanationDesc: 'Here you can find an overview of the different Soli-Contribution types available for the Kollektiv Spinnen Festival.',
    ticketTypesNote: 'Due to the inherent non-profit / community based nature of Kollektiv Spinnen, all Soli-Contributions for our festival include taking over a shift in one of the various roles needed to make all of this happen. Lengths of shifts vary between Standard Soli-Contributions & Reduced Soli-Contributions.',
    ticketTypesNoteAdditional: 'You will select your festival role during the following process, and will be contacted over email at a later point to set your specific shift time.',
    earlyBirdNormalTitle: 'Early Bird / Normal Bird',
    earlyBirdNormalDesc: 'Both Soli-Contribution types are available in Early Bird or Normal Bird varieties depending on when you make your contribution / availability (There will be a limited amount of Early-Bird Soli-Contributions available).',
    whatIsIncludedTitle: 'What is included in my Soli-Contribution?',
    whatIsIncludedDesc: 'All Soli-Contributions include:',
    ticketIncludesAccess: 'Access to the festival',
    ticketIncludesSleeping: 'Access to indoor sleeping options (depending on arrival time / day)',
    ticketIncludesDrinks: 'Non-Alcoholic & Alcoholic Drinks available at the Bar',
    ticketIncludesMeals: '2 Meals per Day available in the Kantine',
    standardTicketType: 'Standard Soli-Contributions',
    standardTicketTypeDesc: 'Standard Soli-Contributions include taking over one 2-hour shift during the festival. You can choose between Early Bird and Normal Bird options depending on availability.',
    reducedTicketType: 'Reduced Soli-Contributions',
    reducedTicketTypeDesc: 'Reduced Soli-Contributions offer a price discount due to the intensity or additional responsibility of the related positions. These Soli-Contributions are for special roles such as Festival-Setup, Festival-Breakdown, Awareness, or Shift Management.',
    reducedTicketTypeReductions: 'The reductions in detail:\n• Festival-Setup (20% Reduction)\n• Festival-Breakdown (40% Reduction - in the form of a refund received after the festival)\n• Awareness (20% Reduction)\n• Shift Management (50% Reduction)\n\nThese reductions will be applied to both the Early Bird & Normal Bird Variants',
    
    // FAQ Page
    searchFAQs: 'Search FAQs...',
    noFAQsAvailable: 'No FAQs Available',
    checkBackLater: 'Check back later for frequently asked questions.',
    found: 'found',
    result: 'result',
    results: 'results',
    noResultsFound: 'No results found',
    noFAQsMatchSearch: 'No FAQs match your search for',
    clearSearch: 'Clear search',
    allgemein: 'General',
    
    // Ticket / Soli-Contribution Checkout
    checkout: 'Checkout',
    paymentProcess: 'Confirmation Process',
    ticketType: 'Soli-Contribution type',
    selectedRole: 'Selected role',
    nA: 'N/A',
    checkoutPlaceholder: 'This is a placeholder checkout page. The full checkout functionality will be implemented here.',
    ticketSummary: 'Soli-Contribution Summary',
    price: 'Contribution',
    purchaserInformation: 'Personal Details',
    fullName: 'Full Name',
    firstName: 'First Name',
    lastName: 'Last Name',
    enterFullName: 'Enter your full name',
    enterEmail: 'Enter your email address',
    notes: 'Additional Notes',
    optional: 'Optional',
    anyAdditionalInformation: 'Any additional information...',
    paymentNote: 'Note: Payment processing will be handled separately. You will receive payment instructions via email after submitting this form.',
    confirmPurchase: 'Confirm Purchase',
    paymentConfirmed: 'Transfer Confirmed',
    processing: 'Processing...',
    ticketPurchaseCreated: 'Soli-Contribution Created',
    ticketPurchaseCreatedDesc: 'Your Soli-Contribution has been registered. You will receive a confirmation email shortly.',
    missingTicketInformation: 'Missing Soli-Contribution information',
    soldOut: 'Sold Out',
    soldOutDesc: 'This Soli-Contribution type is no longer available',
    validationError: 'Validation Error',
    failedToProcessPurchase: 'Failed to process Soli-Contribution',
    remainingTickets: 'Remaining Soli-Contributions',
    unlimited: 'Unlimited',
    pleaseCheckFormErrors: 'Please check the form for errors',
    payWithPayPal: 'Transfer your Soli-Contribution over Paypal Money-Pool',
    checklistItem1: 'Enter your details into the form',
    checklistItem2: 'Generate your personalised Reference Code (Press the generate button)',
    checklistItem3: 'Transfer your Soli-Contribution over the PayPal Link(s) to our Money Pool using your Reference Code (Very Important!)',
    checklistItem4: 'Click the Transfer confirmed button',
    generateReference: 'Generate Reference',
    referenceCodeGenerated: 'Your Reference Code',
    copyReferenceCode: 'Copy Reference Code',
    referenceCodeCopied: 'Reference code copied!',
    allChecklistItemsRequired: 'Please complete all checklist items',
    paypalQRCode: 'PayPal QR Code',
    paypalLink: 'PayPal Link',
    scanQRCode: 'Scan the QR code with your phone to pay',
    orClickLink: 'or click the link',
    paypalPaymentInstructions: 'Please transfer the Soli-Contribution amount of {amount}€ via PayPal before submitting the form.',
    pleaseFillNameBeforeGenerating: 'Please fill in first name and last name before generating reference code',
    referenceCodeGeneratedSuccessfully: 'Reference code generated successfully',
    pleaseGenerateReferenceBeforeConfirming: 'Please generate a reference code before confirming payment',
    checklist: 'Checklist',
    pleaseFollowChecklist: 'Please follow the checklist above to ensure the confirmation process goes through correctly.',
    validEmailFormat: '✓ Valid email format',
    qrCodeImage: 'QR Code Image',
    placeQRCodeInPublicFolder: 'Place paypal-qr-code.png in public folder',
    onlyClickAfterPayment: 'Only click the transfer confirmed button after transferring your Soli-Contribution over PayPal, and completing the checklist at the top of the page.',
    dataStorageConsent: 'I consent to the storage of my data for the purpose of contacting me regarding my shift booking.',
    dataStorageConsentRequired: 'Please consent to data storage to continue.',
    
    // Footer
    sitemap: 'Sitemap',
    sitemapShort: 'Map',
    backToTop: 'Back to Top',
    backToTopShort: 'Top',
    
    // Header
    admin: 'Admin',
    login: 'Login',
    
    // Auth
    signIn: 'Sign In',
    signUp: 'Sign Up',
    welcomeBack: 'Welcome back to Kollektiv Spinnen',
    createAccount: 'Create your account',
    email: 'Email',
    password: 'Password',
    dontHaveAccount: 'Don\'t have an account? Sign up',
    alreadyHaveAccount: 'Already have an account? Sign in',
    backToFestival: 'Back to Festival',
    authenticationError: 'Authentication Error',
    welcomeBackToast: 'Welcome back!',
    signedInSuccessfully: 'You have successfully signed in.',
    accountCreated: 'Account created!',
    checkEmailVerify: 'Please check your email to verify your account.',
    error: 'Error',
    unexpectedError: 'An unexpected error occurred. Please try again.',
    accessDenied: 'Access Denied',
    noAdminPermissions: 'You don\'t have admin permissions.',
    
    // Admin Page
    adminDashboard: 'Admin Dashboard',
    aboutUs: 'About Us',
    signOut: 'Sign Out',
    eventsManagement: 'Events Management',
    faqManagement: 'FAQ Management',
    ticketSettings: 'Soli-Contribution Settings',
    aboutUsManagement: 'About Us Management',
    addEvent: 'Add Event',
    addFAQ: 'Add FAQ',
    searchEvents: 'Search events by title, venue, day, type, or description...',
    showing: 'Showing',
    of: 'of',
    noEventsFound: 'No events found',
    event: 'event',
    events_plural: 'events',
    editEvent: 'Edit Event',
    editFAQ: 'Edit FAQ',
    createNewEvent: 'Create New Event',
    createNewFAQ: 'Create New FAQ',
    hidden: 'Hidden',
    makeVisible: 'Make visible to public',
    hideFromPublic: 'Hide from public',
    loadingTicketSettings: 'Loading Soli-Contribution settings...',
    loadingAboutPageData: 'Loading about page data...',
    earlyBirdTicketSettings: 'Early Bird Soli-Contribution Settings',
    enableEarlyBirdTickets: 'Enable Early Bird Soli-Contributions',
    enableEarlyBirdTicketsDesc: 'When enabled, early bird Soli-Contribution options will be available to guests',
    earlyBirdCutoffDate: 'Early Bird Cutoff Date & Time',
    earlyBirdCutoffDesc: 'Early Bird Soli-Contributions will no longer be available after this date and time',
    ticketAvailabilityLimits: 'Soli-Contribution Availability Limits',
    setMaximumTickets: 'Set the maximum number of Soli-Contributions available for each role. Leave empty for unlimited.',
    standardTickets_plural: 'Standard Soli-Contributions',
    reducedTickets_plural: 'Reduced Soli-Contributions',
    limit: 'Limit',
    ticketPricing: 'Soli-Contribution Pricing',
    setPricesForRoles: 'Set prices for each Soli-Contribution role (in euros). Leave empty to use default pricing.',
    earlyBirdPrice: 'Early Bird Price (€)',
    normalPrice: 'Normal Bird Price (€)',
    saveTicketSettings: 'Save Soli-Contribution Settings',
    pageContent: 'Page Content',
    title: 'Title',
    content: 'Content',
    saveContent: 'Save Content',
    festivalPhotos: 'Festival Photos',
    uploadNewPhoto: 'Upload New Photo',
    upload: 'Upload',
    noPhotosUploaded: 'No photos uploaded yet',
    alignment: 'Alignment',
    size: 'Size',
    caption: 'Caption',
    optionalCaption: 'Optional caption',
    save: 'Save',
    cancel: 'Cancel',
    left: 'Left',
    center: 'Center',
    right: 'Right',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    fullWidth: 'Full Width',
    photoUploadedSuccessfully: 'Photo uploaded successfully',
    photoUpdatedSuccessfully: 'Photo updated successfully',
    photoDeletedSuccessfully: 'Photo deleted successfully',
    failedToUploadPhoto: 'Failed to upload photo',
    failedToUpdatePhoto: 'Failed to update photo',
    failedToDeletePhoto: 'Failed to delete photo',
    areYouSureDeletePhoto: 'Are you sure you want to delete this photo?',
    areYouSureDeleteEvent: 'Are you sure you want to delete this event?',
    areYouSureDeleteFAQ: 'Are you sure you want to delete this FAQ?',
    eventUpdatedSuccessfully: 'Event updated successfully',
    eventCreatedSuccessfully: 'Event created successfully',
    eventDeletedSuccessfully: 'Event deleted successfully',
    eventHiddenFromPublic: 'Event hidden from public',
    eventMadeVisibleToPublic: 'Event made visible to public',
    faqUpdatedSuccessfully: 'FAQ updated successfully',
    faqCreatedSuccessfully: 'FAQ created successfully',
    faqDeletedSuccessfully: 'FAQ deleted successfully',
    faqHiddenFromPublic: 'FAQ hidden from public',
    faqMadeVisibleToPublic: 'FAQ made visible to public',
    ticketSettingsUpdatedSuccessfully: 'Soli-Contribution settings updated successfully',
    aboutPageContentUpdatedSuccessfully: 'About page content updated successfully',
    failedToLoadEvents: 'Failed to load events. Please check your connection and try again.',
    failedToLoadFAQs: 'Failed to load FAQs. Please check your connection and try again.',
    failedToLoadTicketSettings: 'Failed to load Soli-Contribution settings. Please check your connection and try again.',
    failedToLoadAboutPageData: 'Failed to load about page data. Please check your connection and try again.',
    failedToSaveEvent: 'Failed to save event. Please check your connection and try again.',
    failedToDeleteEvent: 'Failed to delete event. Please check your connection and try again.',
    failedToUpdateEventVisibility: 'Failed to update event visibility. Please check your connection and try again.',
    failedToSaveFAQ: 'Failed to save FAQ. Please check your connection and try again.',
    failedToDeleteFAQ: 'Failed to delete FAQ. Please check your connection and try again.',
    failedToUpdateFAQVisibility: 'Failed to update FAQ visibility. Please check your connection and try again.',
    failedToSaveTicketSettings: 'Failed to save ticket settings. Please check your connection and try again.',
    failedToSaveAboutPageContent: 'Failed to save about page content. Please check your connection and try again.',
    hiddenMode: 'Hidden Mode',
    showAll: 'Show All',
    forTheEarlyBirdVariant: 'for the Early Bird variant',
    forTheNormalVariant: 'for the Normal Bird variant',
    remaining: 'remaining',
    
    // Confirmed Soli-Contributions
    purchases: 'Confirmed Soli-Contributions',
    loadingPurchases: 'Loading confirmed Soli-Contributions...',
    noPurchasesYet: 'No confirmed Soli-Contributions yet',
    ticketPurchases: 'Confirmed Soli-Contributions',
    confirm: 'Confirm',
    purchaseConfirmedSuccessfully: 'Soli-Contribution confirmed successfully',
    failedToLoadTicketPurchases: 'Failed to load confirmed Soli-Contributions. Please check your connection and try again.',
    failedToConfirmPurchase: 'Failed to confirm Soli-Contribution. Please check your connection and try again.',
    pending: 'Pending',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    earlyBirdTotalLimit: 'Early Bird Total Limit',
    earlyBirdTotalLimitDesc: 'Set the total number of early-bird Soli-Contributions available across all roles. Leave empty for unlimited. Early-bird Soli-Contributions will automatically become unavailable when this limit is reached.',
    normalTicketSettings: 'Normal Bird Soli-Contribution Settings',
    normalTotalLimit: 'Normal Bird Soli-Contribution Total Limit',
    normalTotalLimitDesc: 'Set the total number of normal bird Soli-Contributions available across all roles. Leave empty for unlimited. Normal bird Soli-Contributions will automatically become unavailable when this limit is reached.',
    universalTicketLimits: 'Universal Soli-Contribution Limits',
    universalTicketLimitsDesc: 'Set the maximum number of Soli-Contributions that can be made across all roles for each contribution type. These limits apply universally to both Early-Bird and Normal Bird Soli-Contributions.',
    
    // Admin - Data Loading
    warning: 'Warning',
    failedToLoadDataSources: 'Failed to load {count} data source(s). Some features may be unavailable.',
    dataSourceEvents: 'Events',
    dataSourceFAQs: 'FAQs',
    dataSourceTicketSettings: 'Ticket Settings',
    dataSourceAboutPage: 'About Page',
    dataSourceTicketPurchases: 'Confirmed Soli-Contributions',
    dataSourceUnknown: 'Data source {index}',
    
    // Admin - URL Validation
    invalidURL: 'Invalid URL',
    urlMustStartWithHttp: 'URL must start with http:// or https://',
    pleaseEnterValidURL: 'Please enter a valid URL',
    lowerNumbersAppearFirst: 'Lower numbers appear first. Use this to control the order of FAQs.',
    
    // Admin - Ticket Purchases
    pendingSoliContributions: 'Pending Soli-Contributions',
    checkedSoliContributions: 'Checked Soli-Contributions',
    loadingCheckedPurchases: 'Loading Checked Soli-Contributions...',
    noCheckedPurchasesYet: 'No checked Soli-Contributions yet',
    checked: 'Checked',
    payment: 'Payment',
    notes: 'Notes',
    failedToUpdateCheckedState: 'Failed to update checked state',
    
    // Admin - Event Form
    eventTitle: 'Title',
    eventTime: 'Time',
    startTime: 'Start Time',
    endTime: 'End Time',
    eventDay: 'Day',
    eventVenue: 'Venue',
    eventType: 'Type',
    descriptionGerman: 'Description (German)',
    descriptionEnglish: 'Description (English)',
    germanDescriptionPlaceholder: 'German description...',
    englishDescriptionPlaceholder: 'English description...',
    selectDay: 'Select day',
    selectVenue: 'Select venue',
    selectType: 'Select type',
    links: 'Links',
    platformPlaceholder: 'Platform (e.g., Instagram, Spotify)',
    urlPlaceholder: 'URL',
    addLink: 'Add Link',
    updateEvent: 'Update Event',
    createEvent: 'Create Event',
    
    // Admin - FAQ Form
    question: 'Question',
    answer: 'Answer',
    enterQuestionPlaceholder: 'Enter the frequently asked question...',
    enterAnswerPlaceholder: 'Enter the answer to the question...',
    displayOrder: 'Display Order',
    visibleToPublic: 'Visible to public',
    updateFAQ: 'Update FAQ',
    createFAQ: 'Create FAQ',
    
    // Admin - Ticket Settings Form
    standardTickets: 'Standard Tickets',
    reducedTickets: 'Reduced Tickets',
    unlimited: 'Unlimited',
    limit: 'Limit',
    
    // Admin - About Page Form
    editFAQ: 'Edit FAQ'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('de');

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations['de']];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};