import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  de: {
    // Header
    search: 'Nach Events suchen...',
    allDays: 'Alle Tage',
    friday: 'Freitag',
    saturday: 'Samstag',
    sunday: 'Sonntag',
    
    // Days (for translation)
    freitag: 'Freitag',
    samstag: 'Samstag',
    sonntag: 'Sonntag',
    filterVenues: 'Venues filtern',
    filterEventTypes: 'Event-Typen filtern',
    days: 'Tage',
    venues: 'Venues',
    events: 'Events',
    clearFilters: 'Filter zurücksetzen',
    year: 'Jahr',
    selectYear: 'Jahr auswählen',
    thisYear: 'Dieses Jahr',
    year: 'Jahr',
    selectYear: 'Jahr auswählen',
    duplicateEvent: 'Event duplizieren',
    duplicateToYear: 'In Jahr duplizieren',
    selectTargetYear: 'Zieljahr auswählen',
    duplicateEventDescription: 'Wählen Sie das Zieljahr aus, in das dieses Event dupliziert werden soll:',
    cannotDuplicateToSameYear: 'Event kann nicht in dasselbe Jahr dupliziert werden',
    eventDuplicatedSuccessfully: 'Event erfolgreich dupliziert',
    duplicatedToYear: 'Dupliziert nach',
    failedToDuplicateEvent: 'Fehler beim Duplizieren des Events',
    pleaseSelectYear: 'Bitte wählen Sie ein Jahr aus',
    gridView: 'Raster',
    listView: 'Liste',
    
    // Venues
    draussen: 'Neue Ufer',
    oben: 'Salon',
    unten: '2000er',
    
    // Event Types
    performance: 'Performance',
    dj: 'DJ',
    workshop: 'Workshop',
    live: 'Konzert',
    interaktiv: 'Interaktiv',
    
    // Grid
    venue: 'VENUE',
    time: 'ZEIT',
    
    // Event Details
    eventDetails: 'Event-Details',
    day: 'Tag',
    venue_label: 'Veranstaltungsort',
    description: 'Beschreibung',
    links: 'Links',
    
    // Empty States
    noEvents: 'Keine Events gefunden',
    noEventsDesc: 'Versuche deine Filter oder Suchbegriffe anzupassen',
    noEventsUpcoming: 'Das Line-up für das nächste Kollektiv Spinnen ist auf dem Weg! Schau dir das Line-up vom letzten Jahr für jetzt an...',
    viewPreviousYear: 'Letztes Jahr anzeigen',
    
    // Common
    close: 'Schließen',
    
    // Event descriptions (translatable)
    welcomeDinnerDesc: 'Beginne dein Festival-Erlebnis mit köstlichem Streetfood und Community-Vibes',
    fireshowDesc: 'Spektakuläre Feuershow, die die Nacht erleuchtet',
    soundJourneyDesc: 'Immersive Klanglandschaft und Gespräch ab 23:00',
    karaokeDesc: 'Sing dich aus voller Kehle mit Freunden in unserer gemütlichen Karaoke-Lounge',
    docuMachlandDesc: 'Dokumentarfilm-Screening und Diskussion über die vier Dimensionen der Nachhaltigkeit',
    yogaFlowDesc: 'Körper-Geist-Verbindung durch fließende Yoga-Bewegungen',
    aerobicTherapyDesc: 'Bewegungstherapie, die Tanz und Wellness kombiniert',
    letterOpeningDesc: 'Interaktive Brieföffnungs-Performance-Kunst',
    soundJourneyLiveDesc: 'Live-Looping Klanglandschaft',
    bowling: 'Interaktives Bowling mit Sekt - Spaß und Spiele für alle',
    
    // FAQ
    faq: 'FAQ',
    faqs: 'FAQs',
    frequentlyAskedQuestions: 'Häufig gestellte Fragen',
    back: 'Zurück',
    
    // Navigation
    timetable: 'Timetable',
    tickets: 'Soli-Beiträge',
    
    // Tickets / Soli-Beiträge
    standardTickets: 'Standard Soli-Beiträge',
    standardTicketsDesc: 'Standard Soli-Beiträge beinhalten generell zwei sehr entspannte Schichten (in der Regel jeweils 2 Stunden) in den unten aufgeführten Rollen. Du kannst deine bevorzugte Option im nächsten Schritt auswählen.',
    earlyBird: 'Early Bird',
    normal: 'Normal Bird',
    reducedTickets: 'Reduzierte Soli-Beiträge',
    reducedTicketsDesc: 'Diese Soli-Beiträge erhalten einen Rabatt aufgrund der Intensität / zusätzlichen Verantwortung der zugehörigen Positionen im Vergleich zu Standard Soli-Beiträgen. Bitte beachte: Einige dieser Positionen sind ausschließlich für Personen mit vorheriger Erfahrung / Expertise verfügbar.',
    chooseThisTicket: 'Diesen Soli-Beitrag wählen',
    roleDescriptions: 'Rollenbeschreibungen',
    bar: 'Bar-Fee',
    barDesc: 'Bar-Fee – Verbreite Magie hinter der Bar! Mixe Drinks, schenke Bier ein und halte die guten Vibes für eine 4h oder zwei 2h Schichten am Laufen. Keine Erfahrung nötig – bring einfach dein Lächeln mit und wir zeigen dir den Rest ✨',
    kuechenhilfe: 'Küchen-Magier:in',
    kuechenhilfeDesc: 'Küchen-Magier:in – Wirke deine kulinarischen Zauber während der Essenszubereitung! Schneide, rühre, serviere und hilf dabei, das Kollektiv zu ernähren. Eine 3h oder zwei 2h Schichten, in denen du einfache Zutaten in Festival-Treibstoff verwandelst 🍳',
    springerRunner: 'Spring-Maus',
    springerRunnerDesc: 'Spring-Maus – Husche herum und halte unsere Räume sauber, unterstütze unsere Bar-Fees, checke Festival-Gäste ein und hilf generell dort, wo es gebraucht wird! Perfekt für alle, die gerne in Bewegung bleiben 🐭 Eine 4h oder zwei 2h Schichten.',
    springerToilet: 'Hygiene-Held:in',
    springerToiletDesc: 'Hygiene-Held:in – Kein Bock auf 2h Schicht? Dann werde zum Toilettenheld und du bist nach nur 2 Sitzungen von 30–45 Minuten im Laufe des Festivals fertig, in denen du Toiletten desinfizierst, Papier auffüllst und Müllbeutel wechselst! 🧻',
    abbau: 'Rückbau-Retter (Abbau)',
    abbauDesc: 'Rückbau-Retter (Abbau) – Hilf uns, den Raum in seinen vor-Party-Glanz zurückzuversetzen! Montag Abbau: Equipment packen, falten, tragen und unseren geliebten DDR-Palast so hinterlassen, wie wir ihn vorgefunden haben 🔧',
    abbauRefundNote: '*Hinweis: Die 40% Reduzierung wird nach dem Festival / nach Abschluss deiner Abbau-Schicht zurückerstattet. Du zahlst also jetzt entweder 99€ (Early-Bird) oder 130€ (Normal-Bird), im Endeffekt aber nur 59€ (Early-Bird) oder 78€ (Normal-Bird).',
    aufbau: 'Aufbau-Ass',
    aufbauDesc: 'Aufbau-Ass (Aufbau) – Sei Teil des Aufbaus der Magie von Grund auf! Freitag Aufbau: Deko aufhängen, Möbel arrangieren, Böden aufbauen und den Raum in unseren Rave-Palast verwandeln 🏗️',
    awareness: 'Care-Crew (Awareness)',
    awarenessDesc: 'Care-Crew (Awareness) – Ein offenes Ohr und ruhige Präsenz, wenn jemand Unterstützung braucht. Du hilfst dabei, dass sich alle sicher und umsorgt fühlen 💜 Eine 4h oder zwei 2h Schichten.',
    techSupport: 'Techniker-Support',
    techSupportDesc: 'Techniker-Support – Halte den Sound am Pumpen und die Lichter am Blinken! Hilf unseren Technikern beim Tragen & Aufbauen von Equipment. Grundlegende technische Kenntnisse ideal (wie man CDJs, Mixer etc. aufbaut) 🎛️ Eine 4h oder zwei 2h Schichten.',
    selectRole: 'Rolle auswählen...',
    roleDescriptionsDesc: 'Detaillierte Rollenbeschreibungen werden hier verfügbar sein.',
    onlyWithExperience: 'Nur mit Erfahrung / Organisatoren-Zustimmung',
    clearSelection: 'Auswahl entfernen',
    ticketTypesExplanation: 'Soli-Beitrags-System Übersicht',
    ticketBirthdayIntro: 'Schön, dass du bei unserem Geburtstag dabei bist! Zur Deckung aller Unkosten zahlt jede:r Gast einen Soli-Beitrag.',
    ticketTypesExplanationDesc: 'Hier findest du eine Übersicht über die verschiedenen Soli-Beitrags-Typen, die für das Kollektiv Spinnen Festival verfügbar sind.',
    ticketTypesNote: 'Aufgrund der inhärenten Non-Profit / Community-basierten Natur von Kollektiv Spinnen beinhalten alle Soli-Beiträge für unser Festival die Übernahme einer längeren (3-4 Std.) oder zwei kürzeren (2 Std.) Schichten in einer der verschiedenen Rollen, die benötigt werden, um all dies möglich zu machen. Die Länge der Schichten variiert sowohl zwischen den Rollen als auch zwischen Standard Soli-Beiträgen & Reduzierten Soli-Beiträgen.',
    ticketTypesNoteAdditional: 'Du wirst deine Festival-Rolle im folgenden Prozess auswählen und wirst später per E-Mail kontaktiert, um deine spezifische Schichtzeit festzulegen.',
    earlyBirdNormalTitle: 'Early Bird / Normal Bird',
    earlyBirdNormalDesc: 'Beide Soli-Beitrags-Typen sind als Early Bird oder Normal Bird erhältlich, abhängig davon, wann du deinen Soli-Beitrag leistest / Verfügbarkeit (Es wird eine begrenzte Anzahl von Early-Bird-Soli-Beiträgen geben).',
    whatIsIncludedTitle: 'Was ist in meinem Soli-Beitrag enthalten?',
    whatIsIncludedDesc: 'Alle Soli-Beiträge beinhalten:',
    ticketIncludesAccess: 'Zugang zum Festival',
    ticketIncludesSleeping: 'Zugang zum Zeltplatz oder (bis zu 80) Indoor-Schlafmöglichkeiten (begrenzte Plätze bitte frühzeitig sichern)',
    ticketIncludesDrinks: 'Alkoholfreie & alkoholische Getränke an der Bar',
    ticketIncludesMeals: '2 Mahlzeiten pro Tag in der Kantine',
    standardTicketType: 'Standard Soli-Beiträge',
    standardTicketTypeDesc: 'Standard Soli-Beiträge beinhalten die Übernahme von zwei Schichten (in der Regel jeweils 2 Stunden) während des Festivals. Du kannst zwischen Early Bird und Normal Bird Soli-Beitrags-Optionen wählen, abhängig von der Verfügbarkeit.',
    reducedTicketType: 'Reduzierte Soli-Beiträge',
    reducedTicketTypeDesc: 'Reduzierte Soli-Beiträge bieten einen Rabatt aufgrund der Intensität oder zusätzlichen Verantwortung der zugehörigen Positionen. Diese Soli-Beiträge sind für spezielle Rollen wie Aufbau, Abbau oder Awareness verfügbar.',
    reducedTicketTypeReductions: 'Die Rabatte im Detail:\n• Aufbau-Ass (20% Rabatt)\n• Care-Crew (Awareness) (20% Rabatt)\n• Rückbau-Retter (Abbau) (40% Rabatt - in Form einer Rückerstattung nach dem Festival)\n• Technik-Support (20% Rabatt)\n\nDiese Rabatte gelten für sowohl Early Bird als auch Normal Bird Varianten.',
    
    // FAQ Page
    searchFAQs: 'FAQs durchsuchen...',
    noFAQsAvailable: 'Keine FAQs verfügbar',
    checkBackLater: 'Schau später nochmal vorbei für häufig gestellte Fragen.',
    found: 'gefunden',
    result: 'Ergebnis',
    results: 'Ergebnisse',
    noResultsFound: 'Keine Ergebnisse gefunden',
    noFAQsMatchSearch: 'Keine FAQs entsprechen der Suche',
    clearSearch: 'Suche zurücksetzen',
    allgemein: 'Allgemein',
    
    // Ticket / Soli-Beitrag Checkout
    checkout: 'Checkout',
    paymentProcess: 'Bestätigungsprozess',
    ticketType: 'Soli-Beitrags-Typ',
    selectedRole: 'Ausgewählte Rolle',
    nA: 'N/A',
    checkoutPlaceholder: 'Dies ist eine Platzhalter-Checkout-Seite. Die vollständige Checkout-Funktionalität wird hier implementiert.',
    ticketSummary: 'Soli-Beitrags-Zusammenfassung',
    price: 'Beitrag',
    purchaserInformation: 'Persönliche Daten',
    fullName: 'Vollständiger Name',
    firstName: 'Vorname',
    lastName: 'Nachname',
    phoneNumber: 'Telefonnummer',
    enterFullName: 'Gib deinen vollständigen Namen ein',
    enterEmail: 'Gib deine E-Mail-Adresse ein',
    enterPhoneNumber: 'Gib deine Telefonnummer ein',
    notes: 'Zusätzliche Notizen',
    optional: 'Optional',
    anyAdditionalInformation: 'Weitere Informationen...',
    paymentNote: 'Hinweis: Die Zahlungsabwicklung erfolgt separat. Du erhältst Zahlungsanweisungen per E-Mail nach dem Absenden dieses Formulars.',
    confirmPurchase: 'Kauf bestätigen',
    paymentConfirmed: 'ANMELDUNG BESTÄTIGEN',
    processing: 'Wird verarbeitet...',
    ticketPurchaseCreated: 'Soli-Beitrags-Kauf erstellt',
    ticketPurchaseCreatedDesc: 'Dein Soli-Beitrags-Kauf wurde registriert.',
    missingTicketInformation: 'Fehlende Soli-Beitrags-Informationen',
    soldOut: 'Ausverkauft',
    soldOutDesc: 'Dieser Soli-Beitrags-Typ ist nicht mehr verfügbar',
    validationError: 'Validierungsfehler',
    failedToProcessPurchase: 'Soli-Beitrags-Kauf konnte nicht verarbeitet werden',
    remainingTickets: 'Verbleibende Soli-Beiträge',
    unlimited: 'Unbegrenzt',
    pleaseCheckFormErrors: 'Bitte überprüfe das Formular auf Fehler',
    payWithPayPal: 'Überweise deinen Soli-Beitrag über PayPal Money-Pool',
    checklistItem1: 'Gib deine Daten in das Formular ein',
    checklistItem2: 'Generiere deinen persönlichen Referenzcode (Drücke den Generieren-Button)',
    checklistItem3: 'Überweise deinen Soli-Beitrag über den/die PayPal-Link(s) zu unserem Money Pool mit deinem Referenzcode (sehr wichtig!)',
    checklistItem4: 'Und klicke auf den Button "Überweisung bestätigt" am Ende der Seite',
    generateReference: 'Referenzcode generieren',
    referenceCodeGenerated: 'Ihr Referenzcode',
    copyReferenceCode: 'Referenzcode kopieren',
    referenceCodeCopied: 'Referenzcode kopiert!',
    allChecklistItemsRequired: 'Bitte alle Checklistenpunkte abschließen',
    paypalQRCode: 'PayPal QR-Code',
    paypalLink: 'PayPal Link',
    openPayPalPool: 'PayPal Money Pool öffnen',
    scanQRCode: 'Scanne den QR-Code mit deinem Handy, um zu überweisen',
    orClickLink: 'oder klicke auf den Link',
    paypalPaymentInstructions: 'Bitte überweise den Betrag von {amount}€ über PayPal, bevor du das Formular absendest.',
    pleaseFillNameBeforeGenerating: 'Bitte fülle Vorname und Nachname aus, bevor du den Referenzcode generierst',
    referenceCodeGeneratedSuccessfully: 'Referenzcode erfolgreich generiert',
    pleaseGenerateReferenceBeforeConfirming: 'Bitte generiere einen Referenzcode, bevor du die Zahlung bestätigst',
    checklist: 'Checkliste',
    pleaseFollowChecklist: 'Bitte folge der Checkliste oben, um sicherzustellen, dass der Bestätigungsprozess korrekt abläuft, und stelle sicher, dass du deine Anmeldung am Ende der Seite bestätigst. Nur dann ist deine Buchung gültig.',
    validEmailFormat: '✓ Gültiges E-Mail-Format',
    qrCodeImage: 'QR-Code Bild',
    placeQRCodeInPublicFolder: 'Platziere paypal-qr-code.png im public Ordner',
    onlyClickAfterPayment: 'Klicke nur auf den Button "ANMELDUNG BESTÄTIGEN", nachdem du deinen Soli-Beitrag über PayPal überwiesen hast und die Checkliste oben abgeschlossen hast.',
    dataStorageConsent: 'Ich stimme zu, dass meine Daten gespeichert werden dürfen, um mich bezüglich meiner Schichtbuchung zu kontaktieren.',
    dataStorageConsentRequired: 'Bitte stimme der Datenspeicherung zu, um fortzufahren.',
    purchaseConfirmed: 'Überweisung Bestätigt',
    purchaseConfirmedDesc: 'Dein Soli-Beitrag wurde erfolgreich registriert.',
    confirmationDetails: 'Bestätigungsdetails',
    confirmationReferenceCode: 'Referenzcode',
    confirmationEmailSent: 'Eine Bestätigungs-E-Mail wird in Kürze an deine E-Mail-Adresse gesendet.',
    returnToTickets: 'Zurück zu Soli-Beiträgen',
    thankYou: 'Vielen Dank!',
    
    // Footer
    sitemap: 'Sitemap',
    sitemapShort: 'Map',
    backToTop: 'Nach oben',
    backToTopShort: 'Oben',
    
    // Header
    admin: 'Admin',
    login: 'Anmelden',
    
    // Auth
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    welcomeBack: 'Willkommen zurück bei Kollektiv Spinnen',
    createAccount: 'Erstelle dein Konto',
    email: 'E-Mail',
    password: 'Passwort',
    dontHaveAccount: 'Noch kein Konto? Registrieren',
    alreadyHaveAccount: 'Bereits ein Konto? Anmelden',
    backToFestival: 'Zurück zum Festival',
    authenticationError: 'Authentifizierungsfehler',
    welcomeBackToast: 'Willkommen zurück!',
    signedInSuccessfully: 'Du hast dich erfolgreich angemeldet.',
    accountCreated: 'Konto erstellt!',
    checkEmailVerify: 'Bitte überprüfe deine E-Mail, um dein Konto zu verifizieren.',
    error: 'Fehler',
    unexpectedError: 'Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut.',
    accessDenied: 'Zugriff verweigert',
    noAdminPermissions: 'Du hast keine Administratorrechte.',
    forgotPassword: 'Passwort vergessen?',
    forgotPasswordDesc: 'Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen deines Passworts.',
    sendResetEmail: 'Reset-E-Mail senden',
    resetEmailSent: 'Reset-E-Mail gesendet',
    resetEmailSentDesc: 'Wir haben dir eine E-Mail mit einem Link zum Zurücksetzen deines Passworts gesendet. Bitte überprüfe dein Postfach.',
    resetPassword: 'Passwort zurücksetzen',
    newPassword: 'Neues Passwort',
    confirmPassword: 'Passwort bestätigen',
    currentPassword: 'Aktuelles Passwort',
    changePassword: 'Passwort ändern',
    passwordChanged: 'Passwort erfolgreich geändert',
    passwordsDoNotMatch: 'Die Passwörter stimmen nicht überein',
    invalidCurrentPassword: 'Das aktuelle Passwort ist falsch',
    adminResetPassword: 'Passwort zurücksetzen',
    adminResetPasswordConfirm: 'Möchtest du wirklich eine Passwort-Reset-E-Mail an {email} senden?',
    adminResetPasswordSent: 'Passwort-Reset-E-Mail wurde an {email} gesendet',
    pleaseEnterValidEmail: 'Bitte gib eine gültige E-Mail-Adresse ein',
    passwordMustBeAtLeast6Characters: 'Das Passwort muss mindestens 6 Zeichen lang sein',
    resetLinkExpired: 'Dieser Passwort-Reset-Link ist abgelaufen. Bitte fordere einen neuen an.',
    resetLinkInvalid: 'Ungültiger oder fehlender Reset-Link. Bitte fordere einen neuen Passwort-Reset an.',
    resetLinkAccessDenied: 'Zugriff verweigert. Bitte fordere einen neuen Passwort-Reset-Link an.',
    requestNewResetLink: 'Neuen Reset-Link anfordern',
    
    // Admin Page
    adminDashboard: 'Admin Dashboard',
    aboutUs: 'Über uns',
    signOut: 'Abmelden',
    eventsManagement: 'Event-Verwaltung',
    faqManagement: 'FAQ-Verwaltung',
    ticketSettings: 'Soli-Beitrags-Einstellungen',
    aboutUsManagement: 'Über uns Verwaltung',
    addEvent: 'Event hinzufügen',
    addFAQ: 'FAQ hinzufügen',
    searchEvents: 'Events nach Titel, Venue, Tag, Typ oder Beschreibung suchen...',
    showing: 'Zeige',
    of: 'von',
    noEventsFound: 'Keine Events gefunden',
    event: 'Event',
    events_plural: 'Events',
    editEvent: 'Event bearbeiten',
    editFAQ: 'FAQ bearbeiten',
    createNewEvent: 'Neues Event erstellen',
    createNewFAQ: 'Neue FAQ erstellen',
    hidden: 'Verborgen',
    makeVisible: 'Öffentlich sichtbar machen',
    hideFromPublic: 'Vor der Öffentlichkeit verbergen',
    loadingTicketSettings: 'Soli-Beitrags-Einstellungen werden geladen...',
    loadingAboutPageData: 'Über uns Seiten-Daten werden geladen...',
    earlyBirdTicketSettings: 'Early Bird Soli-Beitrags-Einstellungen',
    enableEarlyBirdTickets: 'Early Bird Soli-Beiträge aktivieren',
    enableEarlyBirdTicketsDesc: 'Wenn aktiviert, stehen Early Bird Soli-Beitrags-Optionen für Gäste zur Verfügung',
    earlyBirdCutoffDate: 'Early Bird Stichtag & Uhrzeit',
    earlyBirdCutoffDesc: 'Early Bird Soli-Beiträge sind nach diesem Datum und dieser Uhrzeit nicht mehr verfügbar',
    ticketAvailabilityLimits: 'Soli-Beitrags-Verfügbarkeits-Limits',
    setMaximumTickets: 'Setze die maximale Anzahl verfügbarer Soli-Beiträge für jede Rolle. Leer lassen für unbegrenzt.',
    standardTickets_plural: 'Standard Soli-Beiträge',
    reducedTickets_plural: 'Reduzierte Soli-Beiträge',
    limit: 'Limit',
    ticketPricing: 'Soli-Beitrags-Preisgestaltung',
    setPricesForRoles: 'Setze Preise für jede Soli-Beitrags-Rolle (in Euro). Leer lassen für Standard-Preise.',
    earlyBirdPrice: 'Early Bird Preis (€)',
    normalPrice: 'Normal Bird Preis (€)',
    saveTicketSettings: 'Soli-Beitrags-Einstellungen speichern',
    pageContent: 'Seiteninhalt',
    title: 'Titel',
    content: 'Inhalt',
    saveContent: 'Inhalt speichern',
    festivalPhotos: 'Festival-Fotos',
    uploadNewPhoto: 'Neues Foto hochladen',
    upload: 'Hochladen',
    noPhotosUploaded: 'Noch keine Fotos hochgeladen',
    alignment: 'Ausrichtung',
    size: 'Größe',
    caption: 'Bildunterschrift',
    optionalCaption: 'Optionale Bildunterschrift',
    save: 'Speichern',
    cancel: 'Abbrechen',
    left: 'Links',
    center: 'Zentriert',
    right: 'Rechts',
    small: 'Klein',
    medium: 'Mittel',
    large: 'Groß',
    fullWidth: 'Volle Breite',
    photoUploadedSuccessfully: 'Foto erfolgreich hochgeladen',
    photoUpdatedSuccessfully: 'Foto erfolgreich aktualisiert',
    photoDeletedSuccessfully: 'Foto erfolgreich gelöscht',
    failedToUploadPhoto: 'Foto konnte nicht hochgeladen werden',
    failedToUpdatePhoto: 'Foto konnte nicht aktualisiert werden',
    failedToDeletePhoto: 'Foto konnte nicht gelöscht werden',
    areYouSureDeletePhoto: 'Bist du sicher, dass du dieses Foto löschen möchtest?',
    areYouSureDeleteEvent: 'Bist du sicher, dass du dieses Event löschen möchtest?',
    areYouSureDeleteFAQ: 'Bist du sicher, dass du diese FAQ löschen möchtest?',
    eventUpdatedSuccessfully: 'Event erfolgreich aktualisiert',
    eventCreatedSuccessfully: 'Event erfolgreich erstellt',
    eventDeletedSuccessfully: 'Event erfolgreich gelöscht',
    eventHiddenFromPublic: 'Event vor der Öffentlichkeit verborgen',
    eventMadeVisibleToPublic: 'Event für die Öffentlichkeit sichtbar gemacht',
    faqUpdatedSuccessfully: 'FAQ erfolgreich aktualisiert',
    faqCreatedSuccessfully: 'FAQ erfolgreich erstellt',
    faqDeletedSuccessfully: 'FAQ erfolgreich gelöscht',
    faqHiddenFromPublic: 'FAQ vor der Öffentlichkeit verborgen',
    faqMadeVisibleToPublic: 'FAQ für die Öffentlichkeit sichtbar gemacht',
    hideAllFAQs: 'Alle FAQs verbergen',
    areYouSureHideAllFAQs: 'Bist du sicher, dass du alle FAQs verbergen möchtest? Dies macht alle FAQs für die Öffentlichkeit unsichtbar.',
    allFAQsHiddenSuccessfully: 'Alle FAQs erfolgreich verborgen',
    failedToHideAllFAQs: 'Alle FAQs konnten nicht verborgen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    ticketSettingsUpdatedSuccessfully: 'Soli-Beitrags-Einstellungen erfolgreich aktualisiert',
    aboutPageContentUpdatedSuccessfully: 'Über uns Seiteninhalt erfolgreich aktualisiert',
    failedToLoadEvents: 'Events konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToLoadFAQs: 'FAQs konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToLoadTicketSettings: 'Soli-Beitrags-Einstellungen konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToLoadAboutPageData: 'Über uns Seiten-Daten konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToSaveEvent: 'Event konnte nicht gespeichert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToDeleteEvent: 'Event konnte nicht gelöscht werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToUpdateEventVisibility: 'Event-Sichtbarkeit konnte nicht aktualisiert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToSaveFAQ: 'FAQ konnte nicht gespeichert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToDeleteFAQ: 'FAQ konnte nicht gelöscht werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToUpdateFAQVisibility: 'FAQ-Sichtbarkeit konnte nicht aktualisiert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToSaveTicketSettings: 'Ticket-Einstellungen konnten nicht gespeichert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToSaveAboutPageContent: 'Über uns Seiteninhalt konnte nicht gespeichert werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    hiddenMode: 'Versteckter Modus',
    showAll: 'Alle anzeigen',
    forTheEarlyBirdVariant: 'für die Early Bird Variante',
    forTheNormalVariant: 'für die Normal Bird Variante',
    remaining: 'verbleibend',
    
    // Confirmed Soli-Contributions
    purchases: 'Bestätigte Soli-Beiträge',
    loadingPurchases: 'Bestätigte Soli-Beiträge werden geladen...',
    noPurchasesYet: 'Noch keine bestätigten Soli-Beiträge',
    ticketPurchases: 'Bestätigte Soli-Beiträge',
    confirm: 'Bestätigen',
    purchaseConfirmedSuccessfully: 'Soli-Beitrag erfolgreich bestätigt',
    failedToLoadTicketPurchases: 'Bestätigte Soli-Beiträge konnten nicht geladen werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    failedToConfirmPurchase: 'Soli-Beitrag konnte nicht bestätigt werden. Bitte überprüfe deine Verbindung und versuche es erneut.',
    pending: 'Ausstehend',
    confirmed: 'Bestätigt',
    cancelled: 'Storniert',
    earlyBirdTotalLimit: 'Early Bird Gesamtlimit',
    earlyBirdTotalLimitDesc: 'Setze die Gesamtanzahl verfügbarer Early-Bird-Soli-Beiträge für alle Rollen. Leer lassen für unbegrenzt. Early-Bird-Soli-Beiträge werden automatisch nicht mehr verfügbar, wenn dieses Limit erreicht ist.',
    normalTicketSettings: 'Normal Bird Soli-Beitrags-Einstellungen',
    normalTotalLimit: 'Normal Bird Soli-Beitrags-Gesamtlimit',
    normalTotalLimitDesc: 'Setze die Gesamtanzahl verfügbarer Normal Bird Soli-Beiträge für alle Rollen. Leer lassen für unbegrenzt. Normal Bird Soli-Beiträge werden automatisch nicht mehr verfügbar, wenn dieses Limit erreicht ist.',
    universalTicketLimits: 'Universelle Soli-Beitrags-Limits',
    universalTicketLimitsDesc: 'Setze die maximale Anzahl von Soli-Beiträgen, die für jeden Soli-Beitrags-Typ über alle Rollen hinweg geleistet werden können. Diese Limits gelten universell für sowohl Early-Bird- als auch Normal Bird Soli-Beiträge.',
    
    // Admin - Data Loading
    warning: 'Warnung',
    failedToLoadDataSources: 'Fehler beim Laden von {count} Datenquelle(n). Einige Funktionen sind möglicherweise nicht verfügbar.',
    dataSourceEvents: 'Events',
    dataSourceFAQs: 'FAQs',
    dataSourceTicketSettings: 'Ticket-Einstellungen',
    dataSourceAboutPage: 'Über uns Seite',
    dataSourceTicketPurchases: 'Bestätigte Soli-Beiträge',
    dataSourceUnknown: 'Datenquelle {index}',
    
    // Admin - URL Validation
    invalidURL: 'Ungültige URL',
    urlMustStartWithHttp: 'URL muss mit http:// oder https:// beginnen',
    pleaseEnterValidURL: 'Bitte gib eine gültige URL ein',
    lowerNumbersAppearFirst: 'Niedrigere Zahlen erscheinen zuerst. Verwende dies, um die Reihenfolge der FAQs zu steuern.',
    
    // Admin - Ticket Purchases
    pendingSoliContributions: 'Ausstehende Soli-Beiträge',
    checkedSoliContributions: 'Geprüfte Soli-Beiträge',
    cancelledSoliContributions: 'Stornierte Soli-Beiträge',
    loadingCheckedPurchases: 'Geprüfte Soli-Beiträge werden geladen...',
    loadingCancelledPurchases: 'Stornierte Soli-Beiträge werden geladen...',
    noCheckedPurchasesYet: 'Noch keine geprüften Soli-Beiträge',
    noCancelledPurchasesYet: 'Noch keine stornierten Soli-Beiträge',
    failedToCancelPurchase: 'Fehler beim Stornieren des Soli-Beitrags',
    purchaseCancelledSuccessfully: 'Soli-Beitrag erfolgreich storniert',
    reactivate: 'Reaktivieren',
    failedToReactivatePurchase: 'Fehler beim Reaktivieren des Soli-Beitrags',
    purchaseReactivatedSuccessfully: 'Soli-Beitrag erfolgreich reaktiviert',
    delete: 'Löschen',
    confirmDelete: 'Löschen bestätigen',
    areYouSureDeletePurchase: 'Bist du sicher, dass du diesen Soli-Beitrag löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.',
    purchaseDeletedSuccessfully: 'Soli-Beitrag erfolgreich gelöscht',
    failedToDeletePurchase: 'Fehler beim Löschen des Soli-Beitrags',
    checked: 'Geprüft',
    unchecked: 'Nicht geprüft',
    payment: 'Zahlung',
    purchaseNotes: 'Notizen',
    failedToUpdateCheckedState: 'Geprüft-Status konnte nicht aktualisiert werden',
    addSoliContribution: 'Soli-Beitrag hinzufügen',
    editSoliContribution: 'Soli-Beitrag bearbeiten',
    addSoliContributionDesc: 'Manuell einen neuen Soli-Beitrag hinzufügen',
    editSoliContributionDesc: 'Details dieses Soli-Beitrags bearbeiten',
    contributionType: 'Beitragstyp',
    purchaserName: 'Käufername',
    purchaserEmail: 'Käufer-E-Mail',
    purchasePrice: 'Beitragspreis',
    paymentReference: 'Zahlungsreferenz',
    adminCreatePurchaseSuccess: 'Soli-Beitrag erfolgreich erstellt',
    adminUpdatePurchaseSuccess: 'Soli-Beitrag erfolgreich aktualisiert',
    failedToSavePurchase: 'Soli-Beitrag konnte nicht gespeichert werden',
    success: 'Erfolg',
    
    // Admin - Event Form
    eventTitle: 'Titel',
    eventTime: 'Zeit',
    startTime: 'Startzeit',
    endTime: 'Endzeit',
    eventDay: 'Tag',
    eventVenue: 'Veranstaltungsort',
    eventType: 'Typ',
    descriptionGerman: 'Beschreibung (Deutsch)',
    descriptionEnglish: 'Beschreibung (Englisch)',
    germanDescriptionPlaceholder: 'Deutsche Beschreibung...',
    englishDescriptionPlaceholder: 'Englische Beschreibung...',
    selectDay: 'Tag auswählen',
    selectVenue: 'Veranstaltungsort auswählen',
    selectType: 'Typ auswählen',
    eventLinks: 'Links',
    platformPlaceholder: 'Plattform (z.B. Instagram, Spotify)',
    urlPlaceholder: 'URL',
    addLink: 'Link hinzufügen',
    updateEvent: 'Event aktualisieren',
    createEvent: 'Event erstellen',
    
    // Admin - FAQ Form
    question: 'Frage',
    answer: 'Antwort',
    enterQuestionPlaceholder: 'Gib die häufig gestellte Frage ein...',
    enterAnswerPlaceholder: 'Gib die Antwort auf die Frage ein...',
    displayOrder: 'Anzeigereihenfolge',
    visibleToPublic: 'Öffentlich sichtbar',
    updateFAQ: 'FAQ aktualisieren',
    createFAQ: 'FAQ erstellen',
    
    // Admin - About Page Form
    // Note: editFAQ is already defined in FAQ Management section
    
    // Admin - User Management
    users: 'Benutzer',
    userManagement: 'Benutzerverwaltung',
    userEmail: 'E-Mail',
    userFullName: 'Vollständiger Name',
    adminStatus: 'Admin-Status',
    addAdminPrivileges: 'Adminrechte hinzufügen',
    removeAdminPrivileges: 'Adminrechte entfernen',
    isAdmin: 'Admin',
    isSuperAdmin: 'Super Admin',
    notAdmin: 'Kein Administrator',
    adminPrivilegesAdded: 'Adminrechte erfolgreich hinzugefügt',
    adminPrivilegesRemoved: 'Adminrechte erfolgreich entfernt',
    confirmRemoveAdmin: 'Adminrechte entfernen?',
    confirmRemoveAdminDesc: 'Möchten Sie wirklich die Adminrechte von diesem Benutzer entfernen?',
    loadingUsers: 'Benutzer werden geladen...',
    noUsersFound: 'Keine Benutzer gefunden',
    searchUsers: 'Benutzer suchen...',
    cannotRemoveOwnAdmin: 'Sie können Ihre eigenen Adminrechte nicht entfernen',
    invalidEmail: 'Ungültige E-Mail-Adresse',
    userNotFound: 'Benutzer nicht gefunden',
    errorLoadingUsers: 'Fehler beim Laden der Benutzer',
    errorAddingAdmin: 'Fehler beim Hinzufügen der Adminrechte',
    errorRemovingAdmin: 'Fehler beim Entfernen der Adminrechte'
  },
  en: {
    // Header
    search: 'Search events...',
    allDays: 'All Days',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    
    // Days (for translation)
    freitag: 'Friday',
    samstag: 'Saturday',
    sonntag: 'Sunday',
    filterVenues: 'Filter venues',
    filterEventTypes: 'Filter event types',
    days: 'Days',
    venues: 'Venues',
    events: 'Events',
    clearFilters: 'Clear Filters',
    year: 'Year',
    selectYear: 'Select Year',
    thisYear: 'This Year',
    year: 'Year',
    selectYear: 'Select Year',
    duplicateEvent: 'Duplicate Event',
    duplicateToYear: 'Duplicate to Year',
    selectTargetYear: 'Select Target Year',
    duplicateEventDescription: 'Select the target year to duplicate this event to:',
    cannotDuplicateToSameYear: 'Cannot duplicate event to the same year',
    eventDuplicatedSuccessfully: 'Event duplicated successfully',
    duplicatedToYear: 'Duplicated to',
    failedToDuplicateEvent: 'Failed to duplicate event',
    pleaseSelectYear: 'Please select a year',
    gridView: 'Grid',
    listView: 'List',
    
    // Venues
    draussen: 'Neue Ufer',
    oben: 'Salon',
    unten: '2000er',
    
    // Event Types
    performance: 'Performance',
    dj: 'DJ',
    workshop: 'Workshop',
    live: 'Concert',
    interaktiv: 'Interactive',
    
    // Grid
    venue: 'VENUE',
    time: 'TIME',
    
    // Event Details
    eventDetails: 'Event Details',
    day: 'Day',
    venue_label: 'Venue',
    description: 'Description',
    links: 'Links',
    
    // Empty States
    noEvents: 'No events found',
    noEventsDesc: 'Try adjusting your filters or search query',
    noEventsUpcoming: 'The lineup for the next Kollektiv Spinnen is on the way! Check out last years lineup for now...',
    viewPreviousYear: 'View Previous Year',
    
    // Common
    close: 'Close',
    
    // Event descriptions (translatable)
    welcomeDinnerDesc: 'Start your festival experience with delicious street food and community vibes',
    fireshowDesc: 'Spectacular fire performance lighting up the night',
    soundJourneyDesc: 'Immersive sound journey and conversation starting at 23:00',
    karaokeDesc: 'Sing your heart out with friends in our cozy karaoke lounge',
    docuMachlandDesc: 'Documentary screening and discussion about the four dimensions of sustainability',
    yogaFlowDesc: 'Mind-body connection through flowing yoga movements',
    aerobicTherapyDesc: 'Movement therapy combining dance and wellness',
    letterOpeningDesc: 'Interactive letter-opening performance art',
    soundJourneyLiveDesc: 'Live-Looping Soundjourney',
    bowling: 'Interactive bowling with sparkling wine - fun and games for everyone',
    
    // FAQ
    faq: 'FAQ',
    faqs: 'FAQs',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    back: 'Back',
    
    // Navigation
    timetable: 'Timetable',
    tickets: 'Soli-Contributions',
    
    // Tickets / Soli-Contributions
    standardTickets: 'Standard Soli-Contributions',
    standardTicketsDesc: 'Standard Soli-Contributions generally include two very relaxed shifts (usually 2 hours each) in the roles listed below; you can select your preferred option in the next step.',
    earlyBird: 'Early Bird',
    normal: 'Normal Bird',
    reducedTickets: 'Reduced Soli-Contributions',
    reducedTicketsDesc: 'These Soli-Contributions receive a price discount due to the intensity / additional responsibility of the related positions when compared to Standard Soli-Contributions. Please note: Some of these positions are exclusively available to individuals with prior experience / expertise.',
    chooseThisTicket: 'Choose This Soli-Contribution',
    roleDescriptions: 'Role Descriptions',
    bar: 'Bar-Fairy',
    barDesc: 'Bar-Fairy – Spread magic behind the bar! Mix drinks, pour beers, and keep the good vibes flowing for one 4h or two 2h shifts. No experience needed – just bring your smile and we\'ll show you the rest ✨',
    kuechenhilfe: 'Kitchen-Wizard',
    kuechenhilfeDesc: 'Kitchen-Wizard – Cast your culinary spells during meal prep! Chop, stir, serve, and help feed the collective. One 3h or two 2h shifts where you\'ll turn simple ingredients into festival fuel 🍳',
    springerRunner: 'Spring-Mouse',
    springerRunnerDesc: 'Spring-Mouse – Scurry around keeping our spaces tidy, assisting our Bar-Fairies, checking in festival guests, and generally helping where needed! Perfect for those who like to stay moving 🐭 One 4h or two 2h shifts.',
    springerToilet: 'Hygiene-Hero:ine',
    springerToiletDesc: 'Hygiene-Hero:ine – Not in the mood for a full 2h shift? Become our toilet hero and you\'re done after just 2 sessions of 30–45 minutes over the course of the festival, disinfecting toilets, refilling paper, and changing bin bags! 🧻',
    abbau: 'Rebuild-Rescuer (Breakdown)',
    abbauDesc: 'Rebuild-Rescuer (Breakdown) – Help us return the space to its pre-party glory! Monday teardown: packing equipment, folding, carrying, and leaving our beloved DDR palace as we found it 🔧',
    abbauRefundNote: '*Note, the 40% reduction will be refunded after the festival / after your break-down shift has been completed. So you pay either 99€ (Early-Bird) or 130€ (Normal-Bird) now, but in the end only 59€ (Early-Bird) or 78€ (Normal-Bird).',
    aufbau: 'Setup-Ace (Build-Up)',
    aufbauDesc: 'Setup-Ace (Build-Up) – Be part of building the magic from scratch! Friday setup: hanging decorations, arranging furniture, setting up floors, and transforming the space into our rave palace 🏗️',
    awareness: 'Care-Crew (Awareness)',
    awarenessDesc: 'Care-Crew (Awareness) – A listening ear and calm presence when someone needs support. You\'ll help ensure everyone feels safe and cared for 💜 One 4h or two 2h shifts.',
    techSupport: 'Tech-Support',
    techSupportDesc: 'Tech-Support – Keep the sound pumping and lights flashing! Help our technicians with carrying & setting up equipment. Basic technical knowledge ideal (how to set up CDJs, mixer, etc.) 🎛️ One 4h or two 2h shifts.',
    selectRole: 'Select a role...',
    roleDescriptionsDesc: 'Detailed role descriptions will be available here.',
    onlyWithExperience: 'Only with experience / organiser consent',
    clearSelection: 'Clear selection',
    ticketTypesExplanation: 'Soli-Contribution System Overview',
    ticketBirthdayIntro: 'We’re so happy you’re joining us for our birthday! To help cover all costs, each guest contributes a Soli-Contribution.',
    ticketTypesExplanationDesc: 'Here you can find an overview of the different Soli-Contribution types available for the Kollektiv Spinnen Festival.',
    ticketTypesNote: 'Due to the inherent non-profit / community based nature of Kollektiv Spinnen, all Soli-Contributions for our festival include taking over one longer (3-4 hr), or two shorter (2 hr) shifts, in one of the various roles needed to make all of this happen. Lengths of shifts vary between roles as well as Standard Soli-Contributions & Reduced Soli-Contributions.',
    ticketTypesNoteAdditional: 'You will select your festival role during the following process, and will be contacted over email at a later point to set your specific shift time.',
    earlyBirdNormalTitle: 'Early Bird / Normal Bird',
    earlyBirdNormalDesc: 'Both Soli-Contribution types are available in Early Bird or Normal Bird varieties depending on when you make your contribution / availability (There will be a limited amount of Early-Bird Soli-Contributions available).',
    whatIsIncludedTitle: 'What is included in my Soli-Contribution?',
    whatIsIncludedDesc: 'All Soli-Contributions include:',
    ticketIncludesAccess: 'Access to the festival',
    ticketIncludesSleeping: 'Access to the camping area or (up to 80) indoor sleeping options (limited spots, please secure your place early)',
    ticketIncludesDrinks: 'Non-Alcoholic & Alcoholic Drinks available at the Bar',
    ticketIncludesMeals: '2 Meals per Day available in the Kantine',
    standardTicketType: 'Standard Soli-Contributions',
    standardTicketTypeDesc: 'Standard Soli-Contributions include taking over two shifts (usually 2 hours each) during the festival. You can choose between Early Bird and Normal Bird options depending on availability.',
    reducedTicketType: 'Reduced Soli-Contributions',
    reducedTicketTypeDesc: 'Reduced Soli-Contributions offer a price discount due to the intensity or additional responsibility of the related positions. These Soli-Contributions are for special roles such as Festival-Setup, Festival-Breakdown, or Awareness.',
    reducedTicketTypeReductions: 'The reductions in detail:\n\n• Setup-Ace (Build-Up) (20% Reduction)\n• Care-Crew (Awareness) (20% Reduction)\n• Rebuild-Rescuer (Breakdown) (40% Reduction - in the form of a refund received after the festival)\n• Tech-Support (20% Reduction)\n\nThese reductions will be applied to both the Early Bird & Normal Bird variants.',
    
    // FAQ Page
    searchFAQs: 'Search FAQs...',
    noFAQsAvailable: 'No FAQs Available',
    checkBackLater: 'Check back later for frequently asked questions.',
    found: 'found',
    result: 'result',
    results: 'results',
    noResultsFound: 'No results found',
    noFAQsMatchSearch: 'No FAQs match your search for',
    clearSearch: 'Clear search',
    allgemein: 'General',
    
    // Ticket / Soli-Contribution Checkout
    checkout: 'Checkout',
    paymentProcess: 'Confirmation Process',
    ticketType: 'Soli-Contribution type',
    selectedRole: 'Selected role',
    nA: 'N/A',
    checkoutPlaceholder: 'This is a placeholder checkout page. The full checkout functionality will be implemented here.',
    ticketSummary: 'Soli-Contribution Summary',
    price: 'Contribution',
    purchaserInformation: 'Personal Details',
    fullName: 'Full Name',
    firstName: 'First Name',
    lastName: 'Last Name',
    phoneNumber: 'Phone Number',
    enterFullName: 'Enter your full name',
    enterEmail: 'Enter your email address',
    enterPhoneNumber: 'Enter your phone number',
    notes: 'Additional Notes',
    optional: 'Optional',
    anyAdditionalInformation: 'Any additional information...',
    paymentNote: 'Note: Payment processing will be handled separately. You will receive payment instructions via email after submitting this form.',
    confirmPurchase: 'Confirm Purchase',
    paymentConfirmed: 'CONFIRM REGISTRATION',
    processing: 'Processing...',
    ticketPurchaseCreated: 'Soli-Contribution Created',
    ticketPurchaseCreatedDesc: 'Your Soli-Contribution has been registered.',
    missingTicketInformation: 'Missing Soli-Contribution information',
    soldOut: 'Sold Out',
    soldOutDesc: 'This Soli-Contribution type is no longer available',
    validationError: 'Validation Error',
    failedToProcessPurchase: 'Failed to process Soli-Contribution',
    remainingTickets: 'Remaining Soli-Contributions',
    unlimited: 'Unlimited',
    pleaseCheckFormErrors: 'Please check the form for errors',
    payWithPayPal: 'Transfer your Soli-Contribution over Paypal Money-Pool',
    checklistItem1: 'Enter your details into the form',
    checklistItem2: 'Generate your personalised Reference Code (Press the generate button)',
    checklistItem3: 'Transfer your Soli-Contribution over the PayPal Link(s) to our Money Pool using your Reference Code (Very Important!)',
    checklistItem4: 'And click the Transfer Confirmed button at the bottom of the page.',
    generateReference: 'Generate Reference',
    referenceCodeGenerated: 'Your Reference Code',
    copyReferenceCode: 'Copy Reference Code',
    referenceCodeCopied: 'Reference code copied!',
    allChecklistItemsRequired: 'Please complete all checklist items',
    paypalQRCode: 'PayPal QR Code',
    paypalLink: 'PayPal Link',
    openPayPalPool: 'Open PayPal Money Pool',
    scanQRCode: 'Scan the QR code with your phone to transfer',
    orClickLink: 'or click the link',
    paypalPaymentInstructions: 'Please transfer the Soli-Contribution amount of {amount}€ via PayPal before submitting the form.',
    pleaseFillNameBeforeGenerating: 'Please fill in first name and last name before generating reference code',
    referenceCodeGeneratedSuccessfully: 'Reference code generated successfully',
    pleaseGenerateReferenceBeforeConfirming: 'Please generate a reference code before confirming payment',
    checklist: 'Checklist',
    pleaseFollowChecklist: 'Please follow the checklist above to ensure the confirmation process goes through correctly, and ensure you confirm your registration at the bottom of the page. Only then will your booking be valid.',
    validEmailFormat: '✓ Valid email format',
    qrCodeImage: 'QR Code Image',
    placeQRCodeInPublicFolder: 'Place paypal-qr-code.png in public folder',
    onlyClickAfterPayment: 'Only click the CONFIRM REGISTRATION button after transferring your Soli-Contribution over PayPal, and completing the checklist above.',
    dataStorageConsent: 'I consent to the storage of my data for the purpose of contacting me regarding my shift booking.',
    dataStorageConsentRequired: 'Please consent to data storage to continue.',
    purchaseConfirmed: 'Transfer Confirmed',
    purchaseConfirmedDesc: 'Your Soli-Contribution has been successfully registered.',
    confirmationDetails: 'Confirmation Details',
    confirmationReferenceCode: 'Reference Code',
    confirmationEmailSent: 'A confirmation email will be sent to your email address shortly.',
    returnToTickets: 'Return to Soli-Contributions',
    thankYou: 'Thank You!',
    
    // Footer
    sitemap: 'Sitemap',
    sitemapShort: 'Map',
    backToTop: 'Back to Top',
    backToTopShort: 'Top',
    
    // Header
    admin: 'Admin',
    login: 'Login',
    
    // Auth
    signIn: 'Sign In',
    signUp: 'Sign Up',
    welcomeBack: 'Welcome back to Kollektiv Spinnen',
    createAccount: 'Create your account',
    email: 'Email',
    password: 'Password',
    dontHaveAccount: 'Don\'t have an account? Sign up',
    alreadyHaveAccount: 'Already have an account? Sign in',
    backToFestival: 'Back to Festival',
    authenticationError: 'Authentication Error',
    welcomeBackToast: 'Welcome back!',
    signedInSuccessfully: 'You have successfully signed in.',
    accountCreated: 'Account created!',
    checkEmailVerify: 'Please check your email to verify your account.',
    error: 'Error',
    unexpectedError: 'An unexpected error occurred. Please try again.',
    accessDenied: 'Access Denied',
    noAdminPermissions: 'You don\'t have admin permissions.',
    forgotPassword: 'Forgot Password?',
    forgotPasswordDesc: 'Enter your email address and we\'ll send you a link to reset your password.',
    sendResetEmail: 'Send Reset Email',
    resetEmailSent: 'Reset Email Sent',
    resetEmailSentDesc: 'We\'ve sent you an email with a link to reset your password. Please check your inbox.',
    resetPassword: 'Reset Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    currentPassword: 'Current Password',
    changePassword: 'Change Password',
    passwordChanged: 'Password changed successfully',
    passwordsDoNotMatch: 'Passwords do not match',
    invalidCurrentPassword: 'Current password is incorrect',
    adminResetPassword: 'Reset Password',
    adminResetPasswordConfirm: 'Are you sure you want to send a password reset email to {email}?',
    adminResetPasswordSent: 'Password reset email has been sent to {email}',
    pleaseEnterValidEmail: 'Please enter a valid email address',
    passwordMustBeAtLeast6Characters: 'Password must be at least 6 characters',
    resetLinkExpired: 'This password reset link has expired. Please request a new one.',
    resetLinkInvalid: 'Invalid or missing reset link. Please request a new password reset.',
    resetLinkAccessDenied: 'Access denied. Please request a new password reset link.',
    requestNewResetLink: 'Request New Reset Link',
    
    // Admin Page
    adminDashboard: 'Admin Dashboard',
    aboutUs: 'About Us',
    signOut: 'Sign Out',
    eventsManagement: 'Events Management',
    faqManagement: 'FAQ Management',
    ticketSettings: 'Soli-Contribution Settings',
    aboutUsManagement: 'About Us Management',
    addEvent: 'Add Event',
    addFAQ: 'Add FAQ',
    searchEvents: 'Search events by title, venue, day, type, or description...',
    showing: 'Showing',
    of: 'of',
    noEventsFound: 'No events found',
    event: 'event',
    events_plural: 'events',
    editEvent: 'Edit Event',
    editFAQ: 'Edit FAQ',
    createNewEvent: 'Create New Event',
    createNewFAQ: 'Create New FAQ',
    hidden: 'Hidden',
    makeVisible: 'Make visible to public',
    hideFromPublic: 'Hide from public',
    loadingTicketSettings: 'Loading Soli-Contribution settings...',
    loadingAboutPageData: 'Loading about page data...',
    earlyBirdTicketSettings: 'Early Bird Soli-Contribution Settings',
    enableEarlyBirdTickets: 'Enable Early Bird Soli-Contributions',
    enableEarlyBirdTicketsDesc: 'When enabled, early bird Soli-Contribution options will be available to guests',
    earlyBirdCutoffDate: 'Early Bird Cutoff Date & Time',
    earlyBirdCutoffDesc: 'Early Bird Soli-Contributions will no longer be available after this date and time',
    ticketAvailabilityLimits: 'Soli-Contribution Availability Limits',
    setMaximumTickets: 'Set the maximum number of Soli-Contributions available for each role. Leave empty for unlimited.',
    standardTickets_plural: 'Standard Soli-Contributions',
    reducedTickets_plural: 'Reduced Soli-Contributions',
    limit: 'Limit',
    ticketPricing: 'Soli-Contribution Pricing',
    setPricesForRoles: 'Set prices for each Soli-Contribution role (in euros). Leave empty to use default pricing.',
    earlyBirdPrice: 'Early Bird Price (€)',
    normalPrice: 'Normal Bird Price (€)',
    saveTicketSettings: 'Save Soli-Contribution Settings',
    pageContent: 'Page Content',
    title: 'Title',
    content: 'Content',
    saveContent: 'Save Content',
    festivalPhotos: 'Festival Photos',
    uploadNewPhoto: 'Upload New Photo',
    upload: 'Upload',
    noPhotosUploaded: 'No photos uploaded yet',
    alignment: 'Alignment',
    size: 'Size',
    caption: 'Caption',
    optionalCaption: 'Optional caption',
    save: 'Save',
    cancel: 'Cancel',
    left: 'Left',
    center: 'Center',
    right: 'Right',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    fullWidth: 'Full Width',
    photoUploadedSuccessfully: 'Photo uploaded successfully',
    photoUpdatedSuccessfully: 'Photo updated successfully',
    photoDeletedSuccessfully: 'Photo deleted successfully',
    failedToUploadPhoto: 'Failed to upload photo',
    failedToUpdatePhoto: 'Failed to update photo',
    failedToDeletePhoto: 'Failed to delete photo',
    areYouSureDeletePhoto: 'Are you sure you want to delete this photo?',
    areYouSureDeleteEvent: 'Are you sure you want to delete this event?',
    areYouSureDeleteFAQ: 'Are you sure you want to delete this FAQ?',
    eventUpdatedSuccessfully: 'Event updated successfully',
    eventCreatedSuccessfully: 'Event created successfully',
    eventDeletedSuccessfully: 'Event deleted successfully',
    eventHiddenFromPublic: 'Event hidden from public',
    eventMadeVisibleToPublic: 'Event made visible to public',
    faqUpdatedSuccessfully: 'FAQ updated successfully',
    faqCreatedSuccessfully: 'FAQ created successfully',
    faqDeletedSuccessfully: 'FAQ deleted successfully',
    faqHiddenFromPublic: 'FAQ hidden from public',
    faqMadeVisibleToPublic: 'FAQ made visible to public',
    hideAllFAQs: 'Hide All FAQs',
    areYouSureHideAllFAQs: 'Are you sure you want to hide all FAQs? This will make all FAQs invisible to the public.',
    allFAQsHiddenSuccessfully: 'All FAQs hidden successfully',
    failedToHideAllFAQs: 'Failed to hide all FAQs. Please check your connection and try again.',
    ticketSettingsUpdatedSuccessfully: 'Soli-Contribution settings updated successfully',
    aboutPageContentUpdatedSuccessfully: 'About page content updated successfully',
    failedToLoadEvents: 'Failed to load events. Please check your connection and try again.',
    failedToLoadFAQs: 'Failed to load FAQs. Please check your connection and try again.',
    failedToLoadTicketSettings: 'Failed to load Soli-Contribution settings. Please check your connection and try again.',
    failedToLoadAboutPageData: 'Failed to load about page data. Please check your connection and try again.',
    failedToSaveEvent: 'Failed to save event. Please check your connection and try again.',
    failedToDeleteEvent: 'Failed to delete event. Please check your connection and try again.',
    failedToUpdateEventVisibility: 'Failed to update event visibility. Please check your connection and try again.',
    failedToSaveFAQ: 'Failed to save FAQ. Please check your connection and try again.',
    failedToDeleteFAQ: 'Failed to delete FAQ. Please check your connection and try again.',
    failedToUpdateFAQVisibility: 'Failed to update FAQ visibility. Please check your connection and try again.',
    failedToSaveTicketSettings: 'Failed to save ticket settings. Please check your connection and try again.',
    failedToSaveAboutPageContent: 'Failed to save about page content. Please check your connection and try again.',
    hiddenMode: 'Hidden Mode',
    showAll: 'Show All',
    forTheEarlyBirdVariant: 'for the Early Bird variant',
    forTheNormalVariant: 'for the Normal Bird variant',
    remaining: 'remaining',
    
    // Confirmed Soli-Contributions
    purchases: 'Confirmed Soli-Contributions',
    loadingPurchases: 'Loading confirmed Soli-Contributions...',
    noPurchasesYet: 'No confirmed Soli-Contributions yet',
    ticketPurchases: 'Confirmed Soli-Contributions',
    confirm: 'Confirm',
    purchaseConfirmedSuccessfully: 'Soli-Contribution confirmed successfully',
    failedToLoadTicketPurchases: 'Failed to load confirmed Soli-Contributions. Please check your connection and try again.',
    failedToConfirmPurchase: 'Failed to confirm Soli-Contribution. Please check your connection and try again.',
    pending: 'Pending',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    earlyBirdTotalLimit: 'Early Bird Total Limit',
    earlyBirdTotalLimitDesc: 'Set the total number of early-bird Soli-Contributions available across all roles. Leave empty for unlimited. Early-bird Soli-Contributions will automatically become unavailable when this limit is reached.',
    normalTicketSettings: 'Normal Bird Soli-Contribution Settings',
    normalTotalLimit: 'Normal Bird Soli-Contribution Total Limit',
    normalTotalLimitDesc: 'Set the total number of normal bird Soli-Contributions available across all roles. Leave empty for unlimited. Normal bird Soli-Contributions will automatically become unavailable when this limit is reached.',
    universalTicketLimits: 'Universal Soli-Contribution Limits',
    universalTicketLimitsDesc: 'Set the maximum number of Soli-Contributions that can be made across all roles for each contribution type. These limits apply universally to both Early-Bird and Normal Bird Soli-Contributions.',
    
    // Admin - Data Loading
    warning: 'Warning',
    failedToLoadDataSources: 'Failed to load {count} data source(s). Some features may be unavailable.',
    dataSourceEvents: 'Events',
    dataSourceFAQs: 'FAQs',
    dataSourceTicketSettings: 'Ticket Settings',
    dataSourceAboutPage: 'About Page',
    dataSourceTicketPurchases: 'Confirmed Soli-Contributions',
    dataSourceUnknown: 'Data source {index}',
    
    // Admin - URL Validation
    invalidURL: 'Invalid URL',
    urlMustStartWithHttp: 'URL must start with http:// or https://',
    pleaseEnterValidURL: 'Please enter a valid URL',
    lowerNumbersAppearFirst: 'Lower numbers appear first. Use this to control the order of FAQs.',
    
    // Admin - Ticket Purchases
    pendingSoliContributions: 'Pending Soli-Contributions',
    checkedSoliContributions: 'Checked Soli-Contributions',
    cancelledSoliContributions: 'Cancelled Soli-Contributions',
    loadingCheckedPurchases: 'Loading Checked Soli-Contributions...',
    loadingCancelledPurchases: 'Loading Cancelled Soli-Contributions...',
    noCheckedPurchasesYet: 'No checked Soli-Contributions yet',
    noCancelledPurchasesYet: 'No cancelled Soli-Contributions yet',
    failedToCancelPurchase: 'Failed to cancel purchase',
    purchaseCancelledSuccessfully: 'Purchase cancelled successfully',
    reactivate: 'Re-Activate',
    failedToReactivatePurchase: 'Failed to reactivate purchase',
    purchaseReactivatedSuccessfully: 'Purchase reactivated successfully',
    unchecked: 'Unchecked',
    delete: 'Delete',
    confirmDelete: 'Confirm Delete',
    areYouSureDeletePurchase: 'Are you sure you want to delete this Soli-Contribution? This action cannot be undone.',
    purchaseDeletedSuccessfully: 'Purchase deleted successfully',
    failedToDeletePurchase: 'Failed to delete purchase',
    checked: 'Checked',
    payment: 'Payment',
    purchaseNotes: 'Notes',
    failedToUpdateCheckedState: 'Failed to update checked state',
    addSoliContribution: 'Add Soli-Contribution',
    editSoliContribution: 'Edit Soli-Contribution',
    addSoliContributionDesc: 'Manually add a new Soli-Contribution',
    editSoliContributionDesc: 'Edit the details of this Soli-Contribution',
    contributionType: 'Contribution Type',
    purchaserName: 'Purchaser Name',
    purchaserEmail: 'Purchaser Email',
    purchasePrice: 'Contribution Price',
    paymentReference: 'Payment Reference',
    adminCreatePurchaseSuccess: 'Soli-Contribution created successfully',
    adminUpdatePurchaseSuccess: 'Soli-Contribution updated successfully',
    failedToSavePurchase: 'Failed to save Soli-Contribution',
    success: 'Success',
    
    // Admin - Event Form
    eventTitle: 'Title',
    eventTime: 'Time',
    startTime: 'Start Time',
    endTime: 'End Time',
    eventDay: 'Day',
    eventVenue: 'Venue',
    eventType: 'Type',
    descriptionGerman: 'Description (German)',
    descriptionEnglish: 'Description (English)',
    germanDescriptionPlaceholder: 'German description...',
    englishDescriptionPlaceholder: 'English description...',
    selectDay: 'Select day',
    selectVenue: 'Select venue',
    selectType: 'Select type',
    eventLinks: 'Links',
    platformPlaceholder: 'Platform (e.g., Instagram, Spotify)',
    urlPlaceholder: 'URL',
    addLink: 'Add Link',
    updateEvent: 'Update Event',
    createEvent: 'Create Event',
    
    // Admin - FAQ Form
    question: 'Question',
    answer: 'Answer',
    enterQuestionPlaceholder: 'Enter the frequently asked question...',
    enterAnswerPlaceholder: 'Enter the answer to the question...',
    displayOrder: 'Display Order',
    visibleToPublic: 'Visible to public',
    updateFAQ: 'Update FAQ',
    createFAQ: 'Create FAQ',
    
    // Admin - About Page Form
    // Note: editFAQ is already defined in FAQ Management section
    
    // Admin - User Management
    users: 'Users',
    userManagement: 'User Management',
    userEmail: 'Email',
    userFullName: 'Full Name',
    adminStatus: 'Admin Status',
    addAdminPrivileges: 'Add Admin Privileges',
    removeAdminPrivileges: 'Remove Admin Privileges',
    isAdmin: 'Admin',
    isSuperAdmin: 'Super Admin',
    notAdmin: 'Not Admin',
    adminPrivilegesAdded: 'Admin privileges added successfully',
    adminPrivilegesRemoved: 'Admin privileges removed successfully',
    confirmRemoveAdmin: 'Remove Admin Privileges?',
    confirmRemoveAdminDesc: 'Are you sure you want to remove admin privileges from this user?',
    loadingUsers: 'Loading users...',
    noUsersFound: 'No users found',
    searchUsers: 'Search users...',
    cannotRemoveOwnAdmin: 'You cannot remove your own admin privileges',
    invalidEmail: 'Invalid email address',
    userNotFound: 'User not found',
    errorLoadingUsers: 'Error loading users',
    errorAddingAdmin: 'Error adding admin privileges',
    errorRemovingAdmin: 'Error removing admin privileges'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('de');

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations['de']];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};