// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logError } from '@/lib/errorHandler';

// Use environment variables from .env file
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing required environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set. ' +
    'Please ensure your .env file exists in the project root and contains these variables.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: async (url, options = {}) => {
      // 10 second timeout for requests
      const timeoutMs = 10000;
      let timeoutId: NodeJS.Timeout | null = null;
      const timeoutController = new AbortController();
      
      // Set up timeout
      timeoutId = setTimeout(() => {
        if (import.meta.env.DEV) {
          console.warn(`[Supabase] Request timeout after ${timeoutMs}ms`);
        }
        timeoutController.abort();
      }, timeoutMs);
      
      // Merge with existing signal if present
      const existingSignal = options.signal;
      if (existingSignal) {
        // Abort timeout if existing signal aborts
        existingSignal.addEventListener('abort', () => {
          if (timeoutId) clearTimeout(timeoutId);
          timeoutController.abort();
        });
      }
      
      try {
        const response = await fetch(url, {
          ...options,
          signal: existingSignal || timeoutController.signal,
        });
        
        // Clear timeout on success
        if (timeoutId) {
          clearTimeout(timeoutId);
          timeoutId = null;
        }
        
        return response;
      } catch (error: any) {
        // Clear timeout on error
        if (timeoutId) {
          clearTimeout(timeoutId);
          timeoutId = null;
        }
        
        if (error.name === 'AbortError' && timeoutController.signal.aborted) {
          const errorMsg = `Request timeout after ${timeoutMs}ms: ${url}`;
          logError('Supabase', new Error(errorMsg), { url, timeoutMs });
          throw new Error(errorMsg);
        }
        
        logError('Supabase', error, { url, operation: 'fetch' });
        throw error;
      }
    },
  },
});

/**
 * Test the Supabase connection by attempting a simple query
 * @returns Promise<{ success: boolean; error?: any }>
 */
export const testSupabaseConnection = async () => {
  try {
    if (import.meta.env.DEV) {
      console.log('[Supabase] Testing connection...');
    }
    
    // Try a simple query to test connection
    const { data, error } = await supabase
      .from('events')
      .select('id')
      .limit(1);
    
    if (error) {
      logError('Supabase', error, { operation: 'testConnection' });
      return { success: false, error };
    }
    
    if (import.meta.env.DEV) {
      console.log('[Supabase] Connection test successful - found', data?.length || 0, 'events');
    }
    return { success: true, data };
  } catch (err: any) {
    logError('Supabase', err, { operation: 'testConnection' });
    return { success: false, error: err };
  }
};